// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for PlanDetailResponseStatus.
const (
	PlanDetailResponseStatusActive    PlanDetailResponseStatus = "active"
	PlanDetailResponseStatusCompleted PlanDetailResponseStatus = "completed"
	PlanDetailResponseStatusPaused    PlanDetailResponseStatus = "paused"
)

// Valid indicates whether the value is a known member of the PlanDetailResponseStatus enum.
func (e PlanDetailResponseStatus) Valid() bool {
	switch e {
	case PlanDetailResponseStatusActive:
		return true
	case PlanDetailResponseStatusCompleted:
		return true
	case PlanDetailResponseStatusPaused:
		return true
	default:
		return false
	}
}

// Defines values for PlanResponseStatus.
const (
	PlanResponseStatusActive    PlanResponseStatus = "active"
	PlanResponseStatusCompleted PlanResponseStatus = "completed"
	PlanResponseStatusPaused    PlanResponseStatus = "paused"
)

// Valid indicates whether the value is a known member of the PlanResponseStatus enum.
func (e PlanResponseStatus) Valid() bool {
	switch e {
	case PlanResponseStatusActive:
		return true
	case PlanResponseStatusCompleted:
		return true
	case PlanResponseStatusPaused:
		return true
	default:
		return false
	}
}

// Defines values for SkillResponseSource.
const (
	Ai     SkillResponseSource = "ai"
	Manual SkillResponseSource = "manual"
)

// Valid indicates whether the value is a known member of the SkillResponseSource enum.
func (e SkillResponseSource) Valid() bool {
	switch e {
	case Ai:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// AvailabilityItem defines model for AvailabilityItem.
type AvailabilityItem struct {
	// DayOfWeek Go time.Weekday 準拠（0=日曜, 1=月曜, ..., 6=土曜）
	DayOfWeek int `json:"day_of_week"`

	// Hours 勉強可能時間（h）。0.5刻み
	Hours float32 `json:"hours"`
}

// AvailabilityResponse defines model for AvailabilityResponse.
type AvailabilityResponse struct {
	Availability []AvailabilityItem `json:"availability"`
	WeeklyTotal  float32            `json:"weekly_total"`
}

// AvatarPresetResponse defines model for AvatarPresetResponse.
type AvatarPresetResponse struct {
	AvatarPresetId string `json:"avatar_preset_id"`
}

// AvatarResponse defines model for AvatarResponse.
type AvatarResponse struct {
	AvatarPresetId  string               `json:"avatar_preset_id"`
	SkillCategories []SkillCategoryCount `json:"skill_categories"`
	SkillCount      int                  `json:"skill_count"`
}

// CompleteDailyTaskRequest defines model for CompleteDailyTaskRequest.
type CompleteDailyTaskRequest struct {
	ActualEndPage int     `json:"actual_end_page"`
	Memo          *string `json:"memo,omitempty"`
}

// CreatePlanRequest defines model for CreatePlanRequest.
type CreatePlanRequest struct {
	// TargetDate 目標期限（YYYY-MM-DD）。今日より後の日付
	TargetDate openapi_types.Date `json:"target_date"`
	Title      string             `json:"title"`
	TotalPages int                `json:"total_pages"`
}

// CreateSkillRequest defines model for CreateSkillRequest.
type CreateSkillRequest struct {
	Category string `json:"category"`
	Name     string `json:"name"`

	// TaskId タスクに紐付ける場合のみ指定
	TaskId *openapi_types.UUID `json:"task_id,omitempty"`
}

// DailyTaskListResponse defines model for DailyTaskListResponse.
type DailyTaskListResponse struct {
	Date    openapi_types.Date  `json:"date"`
	Summary DailyTaskSummary    `json:"summary"`
	Tasks   []DailyTaskResponse `json:"tasks"`
}

// DailyTaskResponse defines model for DailyTaskResponse.
type DailyTaskResponse struct {
	ActualEndPage *int               `json:"actual_end_page,omitempty"`
	CompletedAt   *time.Time         `json:"completed_at,omitempty"`
	CreatedAt     time.Time          `json:"created_at"`
	Date          openapi_types.Date `json:"date"`
	EndPage       int                `json:"end_page"`
	Id            openapi_types.UUID `json:"id"`
	IsCompleted   bool               `json:"is_completed"`
	Memo          *string            `json:"memo,omitempty"`
	PlanId        openapi_types.UUID `json:"plan_id"`
	PlanTitle     string             `json:"plan_title"`
	StartPage     int                `json:"start_page"`
}

// DailyTaskSummary defines model for DailyTaskSummary.
type DailyTaskSummary struct {
	Completed  int `json:"completed"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExtractSkillsResponse defines model for ExtractSkillsResponse.
type ExtractSkillsResponse struct {
	SuggestedSkills []SuggestedSkill `json:"suggested_skills"`
}

// GenerateDailyTasksRequest defines model for GenerateDailyTasksRequest.
type GenerateDailyTasksRequest struct {
	// Date 対象日（YYYY-MM-DD）。今日以降の日付
	Date openapi_types.Date `json:"date"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PlanDetailResponse defines model for PlanDetailResponse.
type PlanDetailResponse struct {
	AiReview         *string                  `json:"ai_review,omitempty"`
	CreatedAt        time.Time                `json:"created_at"`
	DailyPagesNeeded float32                  `json:"daily_pages_needed"`
	DaysRemaining    int                      `json:"days_remaining"`
	Id               openapi_types.UUID       `json:"id"`
	ProgressRate     float32                  `json:"progress_rate"`
	StartDate        openapi_types.Date       `json:"start_date"`
	Status           PlanDetailResponseStatus `json:"status"`
	TargetDate       openapi_types.Date       `json:"target_date"`
	Title            string                   `json:"title"`
	TotalPages       int                      `json:"total_pages"`
}

// PlanDetailResponseStatus defines model for PlanDetailResponse.Status.
type PlanDetailResponseStatus string

// PlanListResponse defines model for PlanListResponse.
type PlanListResponse struct {
	Plans []PlanResponse `json:"plans"`
}

// PlanResponse defines model for PlanResponse.
type PlanResponse struct {
	AiReview     *string            `json:"ai_review,omitempty"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	ProgressRate float32            `json:"progress_rate"`
	StartDate    openapi_types.Date `json:"start_date"`
	Status       PlanResponseStatus `json:"status"`
	TargetDate   openapi_types.Date `json:"target_date"`
	Title        string             `json:"title"`
	TotalPages   int                `json:"total_pages"`
}

// PlanResponseStatus defines model for PlanResponse.Status.
type PlanResponseStatus string

// PlanReviewResponse defines model for PlanReviewResponse.
type PlanReviewResponse struct {
	AvailableDays int     `json:"available_days"`
	DailyPages    float32 `json:"daily_pages"`
	ReviewMessage string  `json:"review_message"`
	TotalDays     int     `json:"total_days"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// SkillCategoryCount defines model for SkillCategoryCount.
type SkillCategoryCount struct {
	Category string `json:"category"`
	Count    int    `json:"count"`
}

// SkillListResponse defines model for SkillListResponse.
type SkillListResponse struct {
	Skills     []SkillResponse `json:"skills"`
	TotalCount int             `json:"total_count"`
}

// SkillResponse defines model for SkillResponse.
type SkillResponse struct {
	Category  string              `json:"category"`
	CreatedAt time.Time           `json:"created_at"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
	Source    SkillResponseSource `json:"source"`
	TaskId    *openapi_types.UUID `json:"task_id,omitempty"`
}

// SkillResponseSource defines model for SkillResponse.Source.
type SkillResponseSource string

// SuggestedSkill defines model for SuggestedSkill.
type SuggestedSkill struct {
	Category string `json:"category"`
	Name     string `json:"name"`
}

// UpdateAvailabilityRequest defines model for UpdateAvailabilityRequest.
type UpdateAvailabilityRequest struct {
	Availability []AvailabilityItem `json:"availability"`
}

// UpdateAvatarRequest defines model for UpdateAvatarRequest.
type UpdateAvatarRequest struct {
	// AvatarPresetId preset_01 〜 preset_12
	AvatarPresetId string `json:"avatar_preset_id"`
}

// UpdateDailyTaskRequest defines model for UpdateDailyTaskRequest.
type UpdateDailyTaskRequest struct {
	EndPage   int `json:"end_page"`
	StartPage int `json:"start_page"`
}

// UpdateSkillRequest defines model for UpdateSkillRequest.
type UpdateSkillRequest struct {
	Category string `json:"category"`
	Name     string `json:"name"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
}

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// ListDailyTasksParams defines parameters for ListDailyTasks.
type ListDailyTasksParams struct {
	// Date 対象日（YYYY-MM-DD）
	Date openapi_types.Date `form:"date" json:"date"`
}

// ListSkillsParams defines parameters for ListSkills.
type ListSkillsParams struct {
	// Category カテゴリでフィルタ
	Category *string `form:"category,omitempty" json:"category,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// UpdateAvailabilityJSONRequestBody defines body for UpdateAvailability for application/json ContentType.
type UpdateAvailabilityJSONRequestBody = UpdateAvailabilityRequest

// UpdateAvatarJSONRequestBody defines body for UpdateAvatar for application/json ContentType.
type UpdateAvatarJSONRequestBody = UpdateAvatarRequest

// GenerateDailyTasksJSONRequestBody defines body for GenerateDailyTasks for application/json ContentType.
type GenerateDailyTasksJSONRequestBody = GenerateDailyTasksRequest

// UpdateDailyTaskJSONRequestBody defines body for UpdateDailyTask for application/json ContentType.
type UpdateDailyTaskJSONRequestBody = UpdateDailyTaskRequest

// CompleteDailyTaskJSONRequestBody defines body for CompleteDailyTask for application/json ContentType.
type CompleteDailyTaskJSONRequestBody = CompleteDailyTaskRequest

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = CreatePlanRequest

// ReviewPlanJSONRequestBody defines body for ReviewPlan for application/json ContentType.
type ReviewPlanJSONRequestBody = CreatePlanRequest

// CreateSkillJSONRequestBody defines body for CreateSkill for application/json ContentType.
type CreateSkillJSONRequestBody = CreateSkillRequest

// UpdateSkillJSONRequestBody defines body for UpdateSkill for application/json ContentType.
type UpdateSkillJSONRequestBody = UpdateSkillRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ログイン
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// ログアウト
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// アクセストークンを更新
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context) error
	// ユーザー新規登録
	// (POST /auth/signup)
	Signup(ctx echo.Context) error
	// 可処分時間設定を取得
	// (GET /availability)
	GetAvailability(ctx echo.Context) error
	// 可処分時間設定を一括更新
	// (PUT /availability)
	UpdateAvailability(ctx echo.Context) error
	// アバター設定とスキルサマリーを取得
	// (GET /avatar)
	GetAvatar(ctx echo.Context) error
	// アバターのプリセットを設定/変更
	// (PUT /avatar)
	UpdateAvatar(ctx echo.Context) error
	// 指定日のデイリータスク一覧を取得
	// (GET /daily-tasks)
	ListDailyTasks(ctx echo.Context, params ListDailyTasksParams) error
	// 指定日のデイリータスクを自動生成
	// (POST /daily-tasks/generate)
	GenerateDailyTasks(ctx echo.Context) error
	// タスクのページ範囲を手動調整
	// (PUT /daily-tasks/{task_id})
	UpdateDailyTask(ctx echo.Context, taskId openapi_types.UUID) error
	// タスクを完了にする
	// (PATCH /daily-tasks/{task_id}/complete)
	CompleteDailyTask(ctx echo.Context, taskId openapi_types.UUID) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// 計画一覧を取得
	// (GET /plans)
	ListPlans(ctx echo.Context) error
	// 計画を作成
	// (POST /plans)
	CreatePlan(ctx echo.Context) error
	// 計画をAIにレビューしてもらう（保存しない）
	// (POST /plans/review)
	ReviewPlan(ctx echo.Context) error
	// 計画を削除
	// (DELETE /plans/{plan_id})
	DeletePlan(ctx echo.Context, planId openapi_types.UUID) error
	// 計画の詳細を取得
	// (GET /plans/{plan_id})
	GetPlan(ctx echo.Context, planId openapi_types.UUID) error
	// ユーザーの全スキル一覧を取得
	// (GET /skills)
	ListSkills(ctx echo.Context, params ListSkillsParams) error
	// スキルを手動追加
	// (POST /skills)
	CreateSkill(ctx echo.Context) error
	// スキルを削除
	// (DELETE /skills/{skill_id})
	DeleteSkill(ctx echo.Context, skillId openapi_types.UUID) error
	// スキルの名前やカテゴリを更新
	// (PUT /skills/{skill_id})
	UpdateSkill(ctx echo.Context, skillId openapi_types.UUID) error
	// タスクのメモからAIがスキルを抽出（保存しない）
	// (POST /tasks/{task_id}/extract-skills)
	ExtractSkills(ctx echo.Context, taskId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// Signup converts echo context to params.
func (w *ServerInterfaceWrapper) Signup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Signup(ctx)
	return err
}

// GetAvailability converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvailability(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvailability(ctx)
	return err
}

// UpdateAvailability converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAvailability(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAvailability(ctx)
	return err
}

// GetAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatar(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatar(ctx)
	return err
}

// UpdateAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAvatar(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAvatar(ctx)
	return err
}

// ListDailyTasks converts echo context to params.
func (w *ServerInterfaceWrapper) ListDailyTasks(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDailyTasksParams
	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", ctx.QueryParams(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDailyTasks(ctx, params)
	return err
}

// GenerateDailyTasks converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateDailyTasks(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GenerateDailyTasks(ctx)
	return err
}

// UpdateDailyTask converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDailyTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "task_id" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "task_id", ctx.Param("task_id"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter task_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDailyTask(ctx, taskId)
	return err
}

// CompleteDailyTask converts echo context to params.
func (w *ServerInterfaceWrapper) CompleteDailyTask(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "task_id" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "task_id", ctx.Param("task_id"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter task_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CompleteDailyTask(ctx, taskId)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// ListPlans converts echo context to params.
func (w *ServerInterfaceWrapper) ListPlans(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPlans(ctx)
	return err
}

// CreatePlan converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePlan(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePlan(ctx)
	return err
}

// ReviewPlan converts echo context to params.
func (w *ServerInterfaceWrapper) ReviewPlan(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReviewPlan(ctx)
	return err
}

// DeletePlan converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePlan(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "plan_id" -------------
	var planId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "plan_id", ctx.Param("plan_id"), &planId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter plan_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeletePlan(ctx, planId)
	return err
}

// GetPlan converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlan(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "plan_id" -------------
	var planId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "plan_id", ctx.Param("plan_id"), &planId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter plan_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlan(ctx, planId)
	return err
}

// ListSkills converts echo context to params.
func (w *ServerInterfaceWrapper) ListSkills(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSkillsParams
	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", ctx.QueryParams(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSkills(ctx, params)
	return err
}

// CreateSkill converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSkill(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSkill(ctx)
	return err
}

// DeleteSkill converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSkill(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "skill_id" -------------
	var skillId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "skill_id", ctx.Param("skill_id"), &skillId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter skill_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSkill(ctx, skillId)
	return err
}

// UpdateSkill converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSkill(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "skill_id" -------------
	var skillId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "skill_id", ctx.Param("skill_id"), &skillId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter skill_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSkill(ctx, skillId)
	return err
}

// ExtractSkills converts echo context to params.
func (w *ServerInterfaceWrapper) ExtractSkills(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "task_id" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "task_id", ctx.Param("task_id"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter task_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExtractSkills(ctx, taskId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.POST(options.BaseURL+"/auth/signup", wrapper.Signup, options.OperationMiddlewares["signup"]...)
	router.GET(options.BaseURL+"/availability", wrapper.GetAvailability, options.OperationMiddlewares["getAvailability"]...)
	router.PUT(options.BaseURL+"/availability", wrapper.UpdateAvailability, options.OperationMiddlewares["updateAvailability"]...)
	router.GET(options.BaseURL+"/avatar", wrapper.GetAvatar, options.OperationMiddlewares["getAvatar"]...)
	router.PUT(options.BaseURL+"/avatar", wrapper.UpdateAvatar, options.OperationMiddlewares["updateAvatar"]...)
	router.GET(options.BaseURL+"/daily-tasks", wrapper.ListDailyTasks, options.OperationMiddlewares["listDailyTasks"]...)
	router.POST(options.BaseURL+"/daily-tasks/generate", wrapper.GenerateDailyTasks, options.OperationMiddlewares["generateDailyTasks"]...)
	router.PUT(options.BaseURL+"/daily-tasks/:task_id", wrapper.UpdateDailyTask, options.OperationMiddlewares["updateDailyTask"]...)
	router.PATCH(options.BaseURL+"/daily-tasks/:task_id/complete", wrapper.CompleteDailyTask, options.OperationMiddlewares["completeDailyTask"]...)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)
	router.GET(options.BaseURL+"/plans", wrapper.ListPlans, options.OperationMiddlewares["listPlans"]...)
	router.POST(options.BaseURL+"/plans", wrapper.CreatePlan, options.OperationMiddlewares["createPlan"]...)
	router.POST(options.BaseURL+"/plans/review", wrapper.ReviewPlan, options.OperationMiddlewares["reviewPlan"]...)
	router.DELETE(options.BaseURL+"/plans/:plan_id", wrapper.DeletePlan, options.OperationMiddlewares["deletePlan"]...)
	router.GET(options.BaseURL+"/plans/:plan_id", wrapper.GetPlan, options.OperationMiddlewares["getPlan"]...)
	router.GET(options.BaseURL+"/skills", wrapper.ListSkills, options.OperationMiddlewares["listSkills"]...)
	router.POST(options.BaseURL+"/skills", wrapper.CreateSkill, options.OperationMiddlewares["createSkill"]...)
	router.DELETE(options.BaseURL+"/skills/:skill_id", wrapper.DeleteSkill, options.OperationMiddlewares["deleteSkill"]...)
	router.PUT(options.BaseURL+"/skills/:skill_id", wrapper.UpdateSkill, options.OperationMiddlewares["updateSkill"]...)
	router.POST(options.BaseURL+"/tasks/:task_id/extract-skills", wrapper.ExtractSkills, options.OperationMiddlewares["extractSkills"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FxvUxtH0v8q1D7PSxkJx87znKrygrOvctQ5Vy47V1euFKUai7HYIO0quyMnKooqdtdnBBJlQoIxMRfH",
	"jsHEBPAl5EyMbD7MsCt45a9wNTO72n+z0spYAvt4h6SdmZ7uX/+6p6eXcSErF4qyBCWkCulxQc2OwgKg",
	"fw7eBGIeXBfzIioPIVgg3xUVuQgVJEL6xAgoZ+QbmS8hHKMfoZpVxCISZUlICx/LfUgswP6/Qzg2Asp9",
	"1ou7VvWH1/VK6iNrccW6v5zoG/jIWq7Qv/r7+xN9H35kLj+w7i+/rk8LCaEAvhILpYKQ/jAhFESJ/Z1K",
	"CKhchEJaECUEc1ARJhLCqFxS1LAAZnXarD8372wdGC+tJf3w7jev65XR1/VpPKmn+s+blV2s7QkJ4Yas",
	"FAAS0sKNvAyQd+Wz57hLS6XCdbLyREJQ4BclUYEjQvoznzYcoYabg+Trn8MsIuJ69XoFqkVZUmFYt8Dz",
	"FPksIligP/yvAm8IaeF/kq7hkrbVkiGTTdDdDLGx/0d3436wJQOKAsrkSSJ5vpxBMgJ5slJIMa3375M4",
	"MFuEHhBQLitQhailHhBQMkX6WEYcId/ZU6lIEaUcTw7/iOjFj7RsQlDHxHw+kwUI5mTFHhjLTlfJwAts",
	"XPmCXJKoTEF72NPTn93lm8Bvt23/BBxpeXq5IBeKeYjgRSDmy58CdewK/KIEVcTRUBaVQD4DpZFMEeSo",
	"Cpu+MsBz0wIsyPQp8NUlKOXQqJA+n0q5bhVlzsA6XKkVCBC8nAdSpLgIKDmIMiMAwTBVNO5vWmtL1vKD",
	"w6W51/XKtWvXrp355JMzFy8yttjfnbEWV7BewfqM+aqGtU1rcWV/956XPOjEiTBGkIjyMLDts2TXBVFy",
	"Pg/wxhG/oTtW7dG2alMpe3SkqgMKZBL4Z0z49BGtUgrUSJ3aWCoHtjcQY3sSKLyRVoA6Znuj34JY38P6",
	"71jfwtp6Y3tuf/ce1r7GetX8Yducq2BtE2t7Vm3K3PzOa7RSifpJawBSURPuZnnaarrLJVFtQWYO+tqi",
	"Ri0VCoApthWPNJe9aj9vqyg+E3n83BY6REShMMdEpsu4krbUSgueDbNImDmyNimNZAAKqe8MyTJ4OsxS",
	"BHc2JraBWgvMENoGZglBVDPNrXkmui7LeQgkL2eGhhbzQMrEXIY+2+ShMNYQUFDkZgLWpys4i/umTji6",
	"8szn0VNgtz7ztMTOVdcVAuzDUZ3HBs00JuInl1vb8SedyIPCAJfypP+TosgtsgtIfm6fybDHuPN/hRSQ",
	"RZSe1eh11FIuB1WiZRr8O0hQnIF0hbacEFqHJ/PHUIIK8KQWamRg4Udpc+vVwb8eWosrkSF6f3flcGm2",
	"g/jM4zae7JfknBidW8ACEP0ZM/uG54tAVb+UlRhprDNFcwRPrk+gqoIcjEZAgT3QfjnnQd4qJLG6CBEQ",
	"8y2IXMwo8KYIv+RyzJtxsZgvMx/LSBCOwJE4hxIyrqxmFKI+icx0FIIuKnJOgaqaUYJxIXJ1xn7xAz0C",
	"qMRAJJF0jua74k0Y4JsiKKnQCwFvSuRLbOMnpO1SzjiRgJ9benTgl6+536BqudYOmbJt0CBAbZ2BkYAV",
	"nwbZiSJmYsSmjhKrl55ziu6Thu4YuL1CMdC2IJSHGeIVfFrzOFE8ezLgZaKjhLP5qDVDAdQVwDc0EZQ/",
	"tDZPL1fFnFQqRqcJolrMg3KGc5iMcwaNDtveU+n5823CuGeV/090GtQT/k1wlRAuFrU8iYcpJGYFqTmJ",
	"MyRSmtYc22muyWoMUSzrwCjuLuzV/cMidxK9i9Yq7R4rO2AOk6lcUrLQR6YixapU8lVYudWSzkoe9JFg",
	"3aMpQVs6C5weOlNtxP7foCjztyKxh7/cHlXM7HW1vVXtvOVeaNU6ehehorX/CGX/lBrow5PLffangbNt",
	"ARGrps5kbF85jl8y9pcmOqh58msQ0UKfrDrnm2BdhS3qDcFAGR0K34y1ePThhLo28Y1YGWZLiojKV4lf",
	"ObUdeUyEgyWin3FBJNBlXzm8lBZANksSLCSPQcmVCBTFv0DiX0R06YYcdS14sFZpfLuL9fnGehVrq3hS",
	"GxzC2tr+zmTj+TzW1vFkDeu3sD5jVqawXsWTs1ifNzcfNO68wtoS1quDl4eaGWJa+KsofS73se9uQkVl",
	"Sw30p/pTRIlyEUqgKApp4YP+VP8HNAFAo3SnSVBCo8m8nCObHBeKMgMgsR4gEg+NCGlWfhCYkqGK/iiP",
	"lJmWJARZUATFYl7M0hHJz1VZcu9y27GYr7Qx4TclUkqQfsGARQU+m0q9tbV9qKVrB6r6xgbWn2H9MTZ+",
	"tSpz5swDos1zqYG3JoG/UMcV4SE26thYx/ojbExj42es/461V1h7gLUtbHxNPhpb9JlprNUO735zqC1g",
	"7UeCKu0W1qsM404V07cneoDIqZRhCdaHyaNNRMgl1BIS5PeQcc5x7kbsFR9hfRUbFUeRXKnsZ1oIpsAb",
	"ClRHoyW7wh741HbMroEnWPviGq9CDKNvEfzc37buPjs2FD3FxgIBj2Fg/Tk2VryiYa3WuPXQnHFxxa4i",
	"KffUgpYiNtrC+i4FnmcSfZ5tsYXtVHqeijYdO291iWj8h7lYTDPQM6ZpLO0e1n7xoiPVS3TMUYBMUWM+",
	"x8YTas81bPyEjToT5w/HTnk1a/ER1taZprC2gPVaNMet0q38Gxt16+6zg9U7bFQENAPJdw5yoPkxRIP+",
	"BpOuEQu3QYejJ/POXfPV4jExirX89ODp7MFa3ZdCCenP/MnTZ8MTw17LmHe2zKlVs3KbdUQdrG2Ym9+R",
	"1IbuxWsf34lkIiEUSxyrhI9YXSKP6LNcj1OWuOAIh5sTRijvLlb3dyat6s/hYOdHrM0sCChtOIU80V3A",
	"eDvN3hMeoaFhDut72KjbhtHWaAfOBg0cv2HjewrBegS5EK23pxXHNl0kFE9BpfdUEm6APGlU4iSmT7Gx",
	"SAyq75IU1qgMXXwXoYq1zcA+sD7P8Js0H09b97d5KCVUQm82zjSbq7h8cklUkdvdQE/5CihABBWVShmz",
	"nUFIsIrHFyVIy652wcO+Y/LjM+FRbrteh+EuYpnfABeL7HoIZtYWgrXa/s6stfHju4Jg1rhoLa5Q+E7R",
	"2gGjVrvpcX9n8mD1CY9pXdiGcZzM2R050QfCcM9Ol+g4ujmoxwfF2EBufPvAqsydJngBXPf4rOpzDbcH",
	"2DmrMhvtVLC295ZdjsSNqadmdYGtEdflxu07uQnqc9G5TxOG4ShCY0MRoFE3NDgXfbGiQ0QJf7ibeVbo",
	"UqjHqRanzfn0yNaBR5/roSI8XnywWsXaY6xVsT5NUlDtVqepX3OuTWx8R1W709i6Zd7/Bevz1nTVrC4c",
	"PN2zFrY79t+k08BEHRmg7GjYlUMv07zrzhz5dtBJdGdzs7b/4vapO7+P7qzPM+tibZ1dx7by31EI8uwi",
	"mXtq+zP9+cIozI4d93WV/hstvM9ho95Yq5vG7P7ORqi0fo8WWH7Hhob1J/Q+acuze7WsIliwd97sdo08",
	"rl6mT3Rx26GW3PekAMYaCKIPXkT1rMDFPVi5byx26UAVfiWyxwcpf+90WO/7L5dPz09vA4NYn2e6DKOv",
	"yQFJt8M86tKe/H7y8Jh6y3j09VhzgfEzNr6h9/P1xm9z1vfLp9g8GjYHh0iQ9qgVa4tYW8W6TrOA26/r",
	"lf29f5ob9+j3JClgJdBIKI/brx9OsE4XJwf34/ki/d7Gc/uc232j8Yg5d7teHHN65nDp8fGHuh5ngTYa",
	"jp4CNmHFFMkLuFFXfccMhrfLZIHX8U5wUvWOI03bPPjp18b2sxY5HqEm952HyFT7qvNiQstbIayvY+M2",
	"1rdJDNCeYGMB6z/SjH8v4l7I26Df1GEv8Rh+JeR9ueT2tDFhbdP8h3vDHZ34UyS0zfzZmxHdTLV8Le09",
	"zv0Dr/ScJv8n8/LEnKuZc7Nu14ZzbWJu3DOX1zqtzTR7P5zC6t5Lc+YHjme4fJkcZ/+UKFYy57hM+wDu",
	"THqaznWtqOdC5uhFPRc4oaTOQ6bRd2XHAYxuXZR1ztqp3rH26QXZ++t82qY5N2tOz9K3njwpKOetAi+P",
	"B2/FIPvHNGfcfJifBfn+gU1vr8W65D38f8nDQ87MS3PqxbF50UNsPMJarfHTi//SWyiW3TSrTUe5UWa6",
	"JM43OIS1mi8HolZuV9xquhKVQbnp4L+k5IW0kARFMXlzQJgYnvhPAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
