// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for PlanDetailResponseStatus.
const (
	PlanDetailResponseStatusActive    PlanDetailResponseStatus = "active"
	PlanDetailResponseStatusCompleted PlanDetailResponseStatus = "completed"
	PlanDetailResponseStatusPaused    PlanDetailResponseStatus = "paused"
)

// Valid indicates whether the value is a known member of the PlanDetailResponseStatus enum.
func (e PlanDetailResponseStatus) Valid() bool {
	switch e {
	case PlanDetailResponseStatusActive:
		return true
	case PlanDetailResponseStatusCompleted:
		return true
	case PlanDetailResponseStatusPaused:
		return true
	default:
		return false
	}
}

// Defines values for PlanResponseStatus.
const (
	PlanResponseStatusActive    PlanResponseStatus = "active"
	PlanResponseStatusCompleted PlanResponseStatus = "completed"
	PlanResponseStatusPaused    PlanResponseStatus = "paused"
)

// Valid indicates whether the value is a known member of the PlanResponseStatus enum.
func (e PlanResponseStatus) Valid() bool {
	switch e {
	case PlanResponseStatusActive:
		return true
	case PlanResponseStatusCompleted:
		return true
	case PlanResponseStatusPaused:
		return true
	default:
		return false
	}
}

// AvailabilityItem defines model for AvailabilityItem.
type AvailabilityItem struct {
	// DayOfWeek Go time.Weekday 準拠（0=日曜, 1=月曜, ..., 6=土曜）
	DayOfWeek int `json:"day_of_week"`

	// Hours 勉強可能時間（h）。0.5刻み
	Hours float32 `json:"hours"`
}

// AvailabilityResponse defines model for AvailabilityResponse.
type AvailabilityResponse struct {
	Availability []AvailabilityItem `json:"availability"`
	WeeklyTotal  float32            `json:"weekly_total"`
}

// AvatarPresetResponse defines model for AvatarPresetResponse.
type AvatarPresetResponse struct {
	AvatarPresetId string `json:"avatar_preset_id"`
}

// AvatarResponse defines model for AvatarResponse.
type AvatarResponse struct {
	AvatarPresetId  string               `json:"avatar_preset_id"`
	SkillCategories []SkillCategoryCount `json:"skill_categories"`
	SkillCount      int                  `json:"skill_count"`
}

// CreatePlanRequest defines model for CreatePlanRequest.
type CreatePlanRequest struct {
	// TargetDate 目標期限（YYYY-MM-DD）。今日より後の日付
	TargetDate openapi_types.Date `json:"target_date"`
	Title      string             `json:"title"`
	TotalPages int                `json:"total_pages"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// PlanDetailResponse defines model for PlanDetailResponse.
type PlanDetailResponse struct {
	AiReview         *string                  `json:"ai_review,omitempty"`
	CreatedAt        time.Time                `json:"created_at"`
	DailyPagesNeeded float32                  `json:"daily_pages_needed"`
	DaysRemaining    int                      `json:"days_remaining"`
	Id               openapi_types.UUID       `json:"id"`
	ProgressRate     float32                  `json:"progress_rate"`
	StartDate        openapi_types.Date       `json:"start_date"`
	Status           PlanDetailResponseStatus `json:"status"`
	TargetDate       openapi_types.Date       `json:"target_date"`
	Title            string                   `json:"title"`
	TotalPages       int                      `json:"total_pages"`
}

// PlanDetailResponseStatus defines model for PlanDetailResponse.Status.
type PlanDetailResponseStatus string

// PlanListResponse defines model for PlanListResponse.
type PlanListResponse struct {
	Plans []PlanResponse `json:"plans"`
}

// PlanResponse defines model for PlanResponse.
type PlanResponse struct {
	AiReview     *string            `json:"ai_review,omitempty"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	ProgressRate float32            `json:"progress_rate"`
	StartDate    openapi_types.Date `json:"start_date"`
	Status       PlanResponseStatus `json:"status"`
	TargetDate   openapi_types.Date `json:"target_date"`
	Title        string             `json:"title"`
	TotalPages   int                `json:"total_pages"`
}

// PlanResponseStatus defines model for PlanResponse.Status.
type PlanResponseStatus string

// PlanReviewResponse defines model for PlanReviewResponse.
type PlanReviewResponse struct {
	AvailableDays int     `json:"available_days"`
	DailyPages    float32 `json:"daily_pages"`
	ReviewMessage string  `json:"review_message"`
	TotalDays     int     `json:"total_days"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// SkillCategoryCount defines model for SkillCategoryCount.
type SkillCategoryCount struct {
	Category string `json:"category"`
	Count    int    `json:"count"`
}

// UpdateAvailabilityRequest defines model for UpdateAvailabilityRequest.
type UpdateAvailabilityRequest struct {
	Availability []AvailabilityItem `json:"availability"`
}

// UpdateAvatarRequest defines model for UpdateAvatarRequest.
type UpdateAvatarRequest struct {
	// AvatarPresetId preset_01 〜 preset_12
	AvatarPresetId string `json:"avatar_preset_id"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
}

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// UpdateAvailabilityJSONRequestBody defines body for UpdateAvailability for application/json ContentType.
type UpdateAvailabilityJSONRequestBody = UpdateAvailabilityRequest

// UpdateAvatarJSONRequestBody defines body for UpdateAvatar for application/json ContentType.
type UpdateAvatarJSONRequestBody = UpdateAvatarRequest

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = CreatePlanRequest

// ReviewPlanJSONRequestBody defines body for ReviewPlan for application/json ContentType.
type ReviewPlanJSONRequestBody = CreatePlanRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ログイン
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// ログアウト
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// アクセストークンを更新
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context) error
	// ユーザー新規登録
	// (POST /auth/signup)
	Signup(ctx echo.Context) error
	// 可処分時間設定を取得
	// (GET /availability)
	GetAvailability(ctx echo.Context) error
	// 可処分時間設定を一括更新
	// (PUT /availability)
	UpdateAvailability(ctx echo.Context) error
	// アバター設定とスキルサマリーを取得
	// (GET /avatar)
	GetAvatar(ctx echo.Context) error
	// アバターのプリセットを設定/変更
	// (PUT /avatar)
	UpdateAvatar(ctx echo.Context) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// 計画一覧を取得
	// (GET /plans)
	ListPlans(ctx echo.Context) error
	// 計画を作成
	// (POST /plans)
	CreatePlan(ctx echo.Context) error
	// 計画をAIにレビューしてもらう（保存しない）
	// (POST /plans/review)
	ReviewPlan(ctx echo.Context) error
	// 計画を削除
	// (DELETE /plans/{plan_id})
	DeletePlan(ctx echo.Context, planId openapi_types.UUID) error
	// 計画の詳細を取得
	// (GET /plans/{plan_id})
	GetPlan(ctx echo.Context, planId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// Signup converts echo context to params.
func (w *ServerInterfaceWrapper) Signup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Signup(ctx)
	return err
}

// GetAvailability converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvailability(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvailability(ctx)
	return err
}

// UpdateAvailability converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAvailability(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAvailability(ctx)
	return err
}

// GetAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvatar(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvatar(ctx)
	return err
}

// UpdateAvatar converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateAvatar(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateAvatar(ctx)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// ListPlans converts echo context to params.
func (w *ServerInterfaceWrapper) ListPlans(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPlans(ctx)
	return err
}

// CreatePlan converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePlan(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreatePlan(ctx)
	return err
}

// ReviewPlan converts echo context to params.
func (w *ServerInterfaceWrapper) ReviewPlan(ctx echo.Context) error {
	var err error

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReviewPlan(ctx)
	return err
}

// DeletePlan converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePlan(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "plan_id" -------------
	var planId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "plan_id", ctx.Param("plan_id"), &planId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter plan_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeletePlan(ctx, planId)
	return err
}

// GetPlan converts echo context to params.
func (w *ServerInterfaceWrapper) GetPlan(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "plan_id" -------------
	var planId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "plan_id", ctx.Param("plan_id"), &planId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter plan_id: %s", err))
	}

	ctx.Set(string(CookieAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPlan(ctx, planId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken, options.OperationMiddlewares["refreshToken"]...)
	router.POST(options.BaseURL+"/auth/signup", wrapper.Signup, options.OperationMiddlewares["signup"]...)
	router.GET(options.BaseURL+"/availability", wrapper.GetAvailability, options.OperationMiddlewares["getAvailability"]...)
	router.PUT(options.BaseURL+"/availability", wrapper.UpdateAvailability, options.OperationMiddlewares["updateAvailability"]...)
	router.GET(options.BaseURL+"/avatar", wrapper.GetAvatar, options.OperationMiddlewares["getAvatar"]...)
	router.PUT(options.BaseURL+"/avatar", wrapper.UpdateAvatar, options.OperationMiddlewares["updateAvatar"]...)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck, options.OperationMiddlewares["healthCheck"]...)
	router.GET(options.BaseURL+"/plans", wrapper.ListPlans, options.OperationMiddlewares["listPlans"]...)
	router.POST(options.BaseURL+"/plans", wrapper.CreatePlan, options.OperationMiddlewares["createPlan"]...)
	router.POST(options.BaseURL+"/plans/review", wrapper.ReviewPlan, options.OperationMiddlewares["reviewPlan"]...)
	router.DELETE(options.BaseURL+"/plans/:plan_id", wrapper.DeletePlan, options.OperationMiddlewares["deletePlan"]...)
	router.GET(options.BaseURL+"/plans/:plan_id", wrapper.GetPlan, options.OperationMiddlewares["getPlan"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fr/bxPJFf9Xoml/NLHNwbW1xA8pVNeoUCHoqUIosgZ7Yi/Zbzc7G85CkbK76HC+oKShJKRJLz0KIZeQ",
	"BPW4wjU++GMmu05+yr9Qzcza3vXu2r4j3zjxU7K7M/Pe+7zPe/PejO+CgqbomopUYoDcXWAUykiB/N+B",
	"USjJ8JYkS6QySJDC3ulY0xEmEuIjirCS14bzdxAa4Y/IKGBJJ5Kmghz4TOsjkoL6/4rQSBFW+rz/zXtT",
	"/zqoVTMXvIVn3tJyqi97wVuu8v/6+/tTfZ9ecJdXvKXlg9oESAEFfikppgJyn6aAIqni/0wKkIqOQA5I",
	"KkElhMFYCpQ1ExtRBdypCbf22p3Z3nN+9Bbt/fmHB7Vq+aA2QcftTP95t7pDrXcgBYY1rEACcmBY1iAJ",
	"Sj57Lla0aiq3mOSxFMDoC1PCqAhyN0NoNJQaak7Sbt1GBcLUDeJ6DRm6phooii0MjGLPEkEK//BrjIZB",
	"Dvwq3XJc2vdaOuKyMW7NoJj7G25N68HXDGIMK2wk01yu5IlGoMwkRYDpbH9I47bVEnAgEF/FyECkIw4E",
	"4rzOh+WlInvnL2UQLKmlOD3CM5KFv5fYFDBGJFnOFyBBJQ37E3vy03U28aKYV7momSrXqd0f/vL8c0t8",
	"k/jdzA4vEKNtHC4XMYIEXZWheg19YSKDRKEhEJcQyRchQdGgqy9teWuL3vLK/uLsQa1648aNG2euXDlz",
	"6ZKIu92dSW/hGbWr1J50305Ta8tbeLa78zgYhnzhVBRtIhGZS1Tgl5eRWiJlkDubyXBSN56zcfMYA/M6",
	"LAn1m9GdzWT82f5zqhvEQoPwiqkQHnGQ/gFjrQPTEPvcndViWNz6l7WSlOwtpEApHM3iTQxQOjSMOxru",
	"IcQaSzRnxOl1BRkGLKFkyxUxoLu4xsA4KYyqlxCBktwhmKU8RqMSuhMbxQVO+WIekhBMzJ9n2A4WB1UR",
	"SnJFMCCvIlRExV4SJptXMfKYwaeylWKiOgWk8FqmyWM56i2slTAyjDz2A7G7dINA3ArcrgFnEEhMQSKV",
	"BchNAAtEGmVjWU6TEUFFTgLTQEEKBEIvnCp6D/FuQdwlUAVisdEawCCsX9PedmhjvR1xZYhHSUS9LBkd",
	"tjpdhmrve4jI0f5akd2jDRCxdJJaxxk5H9l92tjdA2+vcQ50LVZllGdREZ/WAkHUmz8F8fLJu0TD+CSZ",
	"kfq8pUBoaqpd/4jsOFyuSyXV1BP33aJk6DKs5FWotBct2R6KluRtO1j9nD/fZRsPSPlt6qdu6qmwEbEg",
	"RAvZCBJ+xVmJTyE9VrfNRRpT4rT5XGdcD/dXCe459vaqU7PU0RbepiRbEelSwvW4/ymT7aPjy33+U/Ys",
	"SB1GE/W5gToUtu0RkMzxn7dJxGXFBoe7EJelf1QwsUQq15lvfaJq2oiEBkwWLXeBxOATr0AKCCMALBRY",
	"5iTaCFJbGkFd+hNiPmaqq8Na0lnE3lq1/vcdas/VN6aotUrHrYFBaq3tvhmvv56j1gYdn6b2PdYaVe9T",
	"e4qOP6D2nLu1Up95S61Fak8NXB1spv4c+LOk3tb6xLtRhA0hKtuf6c8wEDUdqVCXQA580p/p/4RHNilz",
	"S9PQJOW0zBoH7jdNkIt5DzKNB4sgJ/oKIEBGBvm9VqwIlFSCRMxCXZelAp+Rvm1oausAqVskhXqWsbAr",
	"CTYRfyGIxRU+m8kcmuwQa7nssK+os0ntl9R+Sp3vvOqsO7nC0DyXyR6aBuGOMFaFb6hTo84GtZ9QZ4I6",
	"L6j9A7XeUmuFWtvU+Rt7dLb5mAlqTe/PP9y3HlHr34xV1j1qTwmOm4oCWeIN2cQrg5LBo5xxfYgNbTJC",
	"M0lHSrDvEeecizK+IfEJtVepU20AGauVP6aDYhgNY2SUkzW7Jgb8xQ/MIyNPe1Mb67wqc4y9zfiz9Mqb",
	"f3liLFqnziNGHseh9mvqPAuqRq3p+r1v3MkWr8SpDc890+2eYj7apvYOJ15gEXtOmNjBdwYvlJJdJwqp",
	"I0o04Sqtp0yTPbZMU1/c2Z/+T5AdmeNkxywnyH3uzNfUec79uUadb6lTE+r87sRT3rS38IRaGwIpaj2i",
	"9nRyjlvlpvyXOjVv/uXe6oyYlUDNtgKwhGKo+RkiA+FT7SNLLLG3AjE4uTPz7tuFE8oo3vL63vqDvbVa",
	"qIQCuZvh4unm0NhQ0DPuzLZ7f9WtfiWuYfbWNt2tf7DShtsS9E+oKma9jBnjlWiZf0TJI7mfOOaSpVdy",
	"RLebU5ZQPlyu7r4Z96ZeRDe7MGP9zEIg7pJT2IijJUzweusXkkf41jBL7XfUqfmOsdbYNmFv8o3je+p8",
	"zSlYS0guDPXuaaXhmyNMKIGm/vhTSfTW9bSlkkZhuk6dBeZQe4eVsE518NKHSFVqbbXZQe05wd+0+3TC",
	"W3oVx1KWSsoIyuI0IjaV/JF/vlhGhZGT7nlY7NX4DlCrr9Vc58Hum81IffaYR+kP1LGo/Zw3JdsBy42K",
	"QZDiW968C4k1/LJkkKt8xBGaHbmw+YVkUXEKtftmfG/1eVyeZNCLLBnbrrV+IXBESTL6E4RjbtvCN2tR",
	"3Hd/XPaqsx+rrPfmICurOJZR9jVzQLp1/5h08sO+nz4+Zg6Zj6EbuFhivKDOQ37IU6t/P+t9vfyRm+/H",
	"zYFBam0EYaXWArVWqW1Te4JaXx3Uqrvv/uluPubv16l1T/xyMZHKd9mfvFQcE8elMhIXx2E+X+LvfT7r",
	"EEMFEYQNrja/k9AhKbduJPwlQTshUwEUu12kDPVyoOtOTO4vPj35rY5JPnd8kn02WNN7q1PUekqtKe58",
	"5u2fSSsBZNyGm9QvnjAZDjeTtf1Y6xQXVR8406ytvW+/q7962aHGE8vi0QalTCyDHEhDXUqPZsHY0Nj/",
	"AwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
