// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Availability is the predicate function for availability builders.
type Availability func(*sql.Selector)

// DailyTask is the predicate function for dailytask builders.
type DailyTask func(*sql.Selector)

// Plan is the predicate function for plan builders.
type Plan func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
