// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/availability"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// Availability is the model entity for the Availability schema.
type Availability struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SunHours holds the value of the "sun_hours" field.
	SunHours float64 `json:"sun_hours,omitempty"`
	// MonHours holds the value of the "mon_hours" field.
	MonHours float64 `json:"mon_hours,omitempty"`
	// TueHours holds the value of the "tue_hours" field.
	TueHours float64 `json:"tue_hours,omitempty"`
	// WedHours holds the value of the "wed_hours" field.
	WedHours float64 `json:"wed_hours,omitempty"`
	// ThuHours holds the value of the "thu_hours" field.
	ThuHours float64 `json:"thu_hours,omitempty"`
	// FriHours holds the value of the "fri_hours" field.
	FriHours float64 `json:"fri_hours,omitempty"`
	// SatHours holds the value of the "sat_hours" field.
	SatHours float64 `json:"sat_hours,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AvailabilityQuery when eager-loading is set.
	Edges               AvailabilityEdges `json:"edges"`
	user_availabilities *uuid.UUID
	selectValues        sql.SelectValues
}

// AvailabilityEdges holds the relations/edges for other nodes in the graph.
type AvailabilityEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AvailabilityEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Availability) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case availability.FieldSunHours, availability.FieldMonHours, availability.FieldTueHours, availability.FieldWedHours, availability.FieldThuHours, availability.FieldFriHours, availability.FieldSatHours:
			values[i] = new(sql.NullFloat64)
		case availability.FieldID:
			values[i] = new(uuid.UUID)
		case availability.ForeignKeys[0]: // user_availabilities
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Availability fields.
func (_m *Availability) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case availability.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case availability.FieldSunHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sun_hours", values[i])
			} else if value.Valid {
				_m.SunHours = value.Float64
			}
		case availability.FieldMonHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field mon_hours", values[i])
			} else if value.Valid {
				_m.MonHours = value.Float64
			}
		case availability.FieldTueHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field tue_hours", values[i])
			} else if value.Valid {
				_m.TueHours = value.Float64
			}
		case availability.FieldWedHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field wed_hours", values[i])
			} else if value.Valid {
				_m.WedHours = value.Float64
			}
		case availability.FieldThuHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field thu_hours", values[i])
			} else if value.Valid {
				_m.ThuHours = value.Float64
			}
		case availability.FieldFriHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fri_hours", values[i])
			} else if value.Valid {
				_m.FriHours = value.Float64
			}
		case availability.FieldSatHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sat_hours", values[i])
			} else if value.Valid {
				_m.SatHours = value.Float64
			}
		case availability.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_availabilities", values[i])
			} else if value.Valid {
				_m.user_availabilities = new(uuid.UUID)
				*_m.user_availabilities = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Availability.
// This includes values selected through modifiers, order, etc.
func (_m *Availability) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Availability entity.
func (_m *Availability) QueryUser() *UserQuery {
	return NewAvailabilityClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Availability.
// Note that you need to call Availability.Unwrap() before calling this method if this Availability
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Availability) Update() *AvailabilityUpdateOne {
	return NewAvailabilityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Availability entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Availability) Unwrap() *Availability {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Availability is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Availability) String() string {
	var builder strings.Builder
	builder.WriteString("Availability(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sun_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.SunHours))
	builder.WriteString(", ")
	builder.WriteString("mon_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonHours))
	builder.WriteString(", ")
	builder.WriteString("tue_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.TueHours))
	builder.WriteString(", ")
	builder.WriteString("wed_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.WedHours))
	builder.WriteString(", ")
	builder.WriteString("thu_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThuHours))
	builder.WriteString(", ")
	builder.WriteString("fri_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.FriHours))
	builder.WriteString(", ")
	builder.WriteString("sat_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.SatHours))
	builder.WriteByte(')')
	return builder.String()
}

// Availabilities is a parsable slice of Availability.
type Availabilities []*Availability
