// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/availability"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// Availability is the model entity for the Availability schema.
type Availability struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DayOfWeek holds the value of the "day_of_week" field.
	DayOfWeek int8 `json:"day_of_week,omitempty"`
	// Hours holds the value of the "hours" field.
	Hours float64 `json:"hours,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AvailabilityQuery when eager-loading is set.
	Edges               AvailabilityEdges `json:"edges"`
	user_availabilities *uuid.UUID
	selectValues        sql.SelectValues
}

// AvailabilityEdges holds the relations/edges for other nodes in the graph.
type AvailabilityEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AvailabilityEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Availability) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case availability.FieldHours:
			values[i] = new(sql.NullFloat64)
		case availability.FieldDayOfWeek:
			values[i] = new(sql.NullInt64)
		case availability.FieldID:
			values[i] = new(uuid.UUID)
		case availability.ForeignKeys[0]: // user_availabilities
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Availability fields.
func (_m *Availability) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case availability.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case availability.FieldDayOfWeek:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field day_of_week", values[i])
			} else if value.Valid {
				_m.DayOfWeek = int8(value.Int64)
			}
		case availability.FieldHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hours", values[i])
			} else if value.Valid {
				_m.Hours = value.Float64
			}
		case availability.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_availabilities", values[i])
			} else if value.Valid {
				_m.user_availabilities = new(uuid.UUID)
				*_m.user_availabilities = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Availability.
// This includes values selected through modifiers, order, etc.
func (_m *Availability) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Availability entity.
func (_m *Availability) QueryUser() *UserQuery {
	return NewAvailabilityClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Availability.
// Note that you need to call Availability.Unwrap() before calling this method if this Availability
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Availability) Update() *AvailabilityUpdateOne {
	return NewAvailabilityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Availability entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Availability) Unwrap() *Availability {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Availability is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Availability) String() string {
	var builder strings.Builder
	builder.WriteString("Availability(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("day_of_week=")
	builder.WriteString(fmt.Sprintf("%v", _m.DayOfWeek))
	builder.WriteString(", ")
	builder.WriteString("hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hours))
	builder.WriteByte(')')
	return builder.String()
}

// Availabilities is a parsable slice of Availability.
type Availabilities []*Availability
