// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/availability"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// AvailabilityUpdate is the builder for updating Availability entities.
type AvailabilityUpdate struct {
	config
	hooks    []Hook
	mutation *AvailabilityMutation
}

// Where appends a list predicates to the AvailabilityUpdate builder.
func (_u *AvailabilityUpdate) Where(ps ...predicate.Availability) *AvailabilityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *AvailabilityUpdate) SetDayOfWeek(v int8) *AvailabilityUpdate {
	_u.mutation.ResetDayOfWeek()
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableDayOfWeek(v *int8) *AvailabilityUpdate {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// AddDayOfWeek adds value to the "day_of_week" field.
func (_u *AvailabilityUpdate) AddDayOfWeek(v int8) *AvailabilityUpdate {
	_u.mutation.AddDayOfWeek(v)
	return _u
}

// SetHours sets the "hours" field.
func (_u *AvailabilityUpdate) SetHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetHours()
	_u.mutation.SetHours(v)
	return _u
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetHours(*v)
	}
	return _u
}

// AddHours adds value to the "hours" field.
func (_u *AvailabilityUpdate) AddHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddHours(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AvailabilityUpdate) SetUserID(id uuid.UUID) *AvailabilityUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AvailabilityUpdate) SetUser(v *User) *AvailabilityUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_u *AvailabilityUpdate) Mutation() *AvailabilityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AvailabilityUpdate) ClearUser() *AvailabilityUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AvailabilityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AvailabilityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityUpdate) check() error {
	if v, ok := _u.mutation.DayOfWeek(); ok {
		if err := availability.DayOfWeekValidator(v); err != nil {
			return &ValidationError{Name: "day_of_week", err: fmt.Errorf(`ent: validator failed for field "Availability.day_of_week": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hours(); ok {
		if err := availability.HoursValidator(v); err != nil {
			return &ValidationError{Name: "hours", err: fmt.Errorf(`ent: validator failed for field "Availability.hours": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.user"`)
	}
	return nil
}

func (_u *AvailabilityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availability.Table, availability.Columns, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(availability.FieldDayOfWeek, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDayOfWeek(); ok {
		_spec.AddField(availability.FieldDayOfWeek, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Hours(); ok {
		_spec.SetField(availability.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHours(); ok {
		_spec.AddField(availability.FieldHours, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AvailabilityUpdateOne is the builder for updating a single Availability entity.
type AvailabilityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AvailabilityMutation
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *AvailabilityUpdateOne) SetDayOfWeek(v int8) *AvailabilityUpdateOne {
	_u.mutation.ResetDayOfWeek()
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableDayOfWeek(v *int8) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// AddDayOfWeek adds value to the "day_of_week" field.
func (_u *AvailabilityUpdateOne) AddDayOfWeek(v int8) *AvailabilityUpdateOne {
	_u.mutation.AddDayOfWeek(v)
	return _u
}

// SetHours sets the "hours" field.
func (_u *AvailabilityUpdateOne) SetHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetHours()
	_u.mutation.SetHours(v)
	return _u
}

// SetNillableHours sets the "hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetHours(*v)
	}
	return _u
}

// AddHours adds value to the "hours" field.
func (_u *AvailabilityUpdateOne) AddHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddHours(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AvailabilityUpdateOne) SetUserID(id uuid.UUID) *AvailabilityUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AvailabilityUpdateOne) SetUser(v *User) *AvailabilityUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_u *AvailabilityUpdateOne) Mutation() *AvailabilityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AvailabilityUpdateOne) ClearUser() *AvailabilityUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AvailabilityUpdate builder.
func (_u *AvailabilityUpdateOne) Where(ps ...predicate.Availability) *AvailabilityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AvailabilityUpdateOne) Select(field string, fields ...string) *AvailabilityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Availability entity.
func (_u *AvailabilityUpdateOne) Save(ctx context.Context) (*Availability, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityUpdateOne) SaveX(ctx context.Context) *Availability {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AvailabilityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityUpdateOne) check() error {
	if v, ok := _u.mutation.DayOfWeek(); ok {
		if err := availability.DayOfWeekValidator(v); err != nil {
			return &ValidationError{Name: "day_of_week", err: fmt.Errorf(`ent: validator failed for field "Availability.day_of_week": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hours(); ok {
		if err := availability.HoursValidator(v); err != nil {
			return &ValidationError{Name: "hours", err: fmt.Errorf(`ent: validator failed for field "Availability.hours": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.user"`)
	}
	return nil
}

func (_u *AvailabilityUpdateOne) sqlSave(ctx context.Context) (_node *Availability, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availability.Table, availability.Columns, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Availability.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, availability.FieldID)
		for _, f := range fields {
			if !availability.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != availability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(availability.FieldDayOfWeek, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDayOfWeek(); ok {
		_spec.AddField(availability.FieldDayOfWeek, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Hours(); ok {
		_spec.SetField(availability.FieldHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHours(); ok {
		_spec.AddField(availability.FieldHours, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Availability{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
