// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/availability"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// AvailabilityUpdate is the builder for updating Availability entities.
type AvailabilityUpdate struct {
	config
	hooks    []Hook
	mutation *AvailabilityMutation
}

// Where appends a list predicates to the AvailabilityUpdate builder.
func (_u *AvailabilityUpdate) Where(ps ...predicate.Availability) *AvailabilityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSunHours sets the "sun_hours" field.
func (_u *AvailabilityUpdate) SetSunHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetSunHours()
	_u.mutation.SetSunHours(v)
	return _u
}

// SetNillableSunHours sets the "sun_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableSunHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetSunHours(*v)
	}
	return _u
}

// AddSunHours adds value to the "sun_hours" field.
func (_u *AvailabilityUpdate) AddSunHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddSunHours(v)
	return _u
}

// SetMonHours sets the "mon_hours" field.
func (_u *AvailabilityUpdate) SetMonHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetMonHours()
	_u.mutation.SetMonHours(v)
	return _u
}

// SetNillableMonHours sets the "mon_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableMonHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetMonHours(*v)
	}
	return _u
}

// AddMonHours adds value to the "mon_hours" field.
func (_u *AvailabilityUpdate) AddMonHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddMonHours(v)
	return _u
}

// SetTueHours sets the "tue_hours" field.
func (_u *AvailabilityUpdate) SetTueHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetTueHours()
	_u.mutation.SetTueHours(v)
	return _u
}

// SetNillableTueHours sets the "tue_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableTueHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetTueHours(*v)
	}
	return _u
}

// AddTueHours adds value to the "tue_hours" field.
func (_u *AvailabilityUpdate) AddTueHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddTueHours(v)
	return _u
}

// SetWedHours sets the "wed_hours" field.
func (_u *AvailabilityUpdate) SetWedHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetWedHours()
	_u.mutation.SetWedHours(v)
	return _u
}

// SetNillableWedHours sets the "wed_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableWedHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetWedHours(*v)
	}
	return _u
}

// AddWedHours adds value to the "wed_hours" field.
func (_u *AvailabilityUpdate) AddWedHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddWedHours(v)
	return _u
}

// SetThuHours sets the "thu_hours" field.
func (_u *AvailabilityUpdate) SetThuHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetThuHours()
	_u.mutation.SetThuHours(v)
	return _u
}

// SetNillableThuHours sets the "thu_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableThuHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetThuHours(*v)
	}
	return _u
}

// AddThuHours adds value to the "thu_hours" field.
func (_u *AvailabilityUpdate) AddThuHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddThuHours(v)
	return _u
}

// SetFriHours sets the "fri_hours" field.
func (_u *AvailabilityUpdate) SetFriHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetFriHours()
	_u.mutation.SetFriHours(v)
	return _u
}

// SetNillableFriHours sets the "fri_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableFriHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetFriHours(*v)
	}
	return _u
}

// AddFriHours adds value to the "fri_hours" field.
func (_u *AvailabilityUpdate) AddFriHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddFriHours(v)
	return _u
}

// SetSatHours sets the "sat_hours" field.
func (_u *AvailabilityUpdate) SetSatHours(v float64) *AvailabilityUpdate {
	_u.mutation.ResetSatHours()
	_u.mutation.SetSatHours(v)
	return _u
}

// SetNillableSatHours sets the "sat_hours" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableSatHours(v *float64) *AvailabilityUpdate {
	if v != nil {
		_u.SetSatHours(*v)
	}
	return _u
}

// AddSatHours adds value to the "sat_hours" field.
func (_u *AvailabilityUpdate) AddSatHours(v float64) *AvailabilityUpdate {
	_u.mutation.AddSatHours(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AvailabilityUpdate) SetUserID(id uuid.UUID) *AvailabilityUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AvailabilityUpdate) SetUser(v *User) *AvailabilityUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_u *AvailabilityUpdate) Mutation() *AvailabilityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AvailabilityUpdate) ClearUser() *AvailabilityUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AvailabilityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AvailabilityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityUpdate) check() error {
	if v, ok := _u.mutation.SunHours(); ok {
		if err := availability.SunHoursValidator(v); err != nil {
			return &ValidationError{Name: "sun_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.sun_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MonHours(); ok {
		if err := availability.MonHoursValidator(v); err != nil {
			return &ValidationError{Name: "mon_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.mon_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TueHours(); ok {
		if err := availability.TueHoursValidator(v); err != nil {
			return &ValidationError{Name: "tue_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.tue_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WedHours(); ok {
		if err := availability.WedHoursValidator(v); err != nil {
			return &ValidationError{Name: "wed_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.wed_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThuHours(); ok {
		if err := availability.ThuHoursValidator(v); err != nil {
			return &ValidationError{Name: "thu_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.thu_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FriHours(); ok {
		if err := availability.FriHoursValidator(v); err != nil {
			return &ValidationError{Name: "fri_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.fri_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SatHours(); ok {
		if err := availability.SatHoursValidator(v); err != nil {
			return &ValidationError{Name: "sat_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.sat_hours": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.user"`)
	}
	return nil
}

func (_u *AvailabilityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availability.Table, availability.Columns, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SunHours(); ok {
		_spec.SetField(availability.FieldSunHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSunHours(); ok {
		_spec.AddField(availability.FieldSunHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonHours(); ok {
		_spec.SetField(availability.FieldMonHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonHours(); ok {
		_spec.AddField(availability.FieldMonHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TueHours(); ok {
		_spec.SetField(availability.FieldTueHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTueHours(); ok {
		_spec.AddField(availability.FieldTueHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WedHours(); ok {
		_spec.SetField(availability.FieldWedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWedHours(); ok {
		_spec.AddField(availability.FieldWedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ThuHours(); ok {
		_spec.SetField(availability.FieldThuHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThuHours(); ok {
		_spec.AddField(availability.FieldThuHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FriHours(); ok {
		_spec.SetField(availability.FieldFriHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFriHours(); ok {
		_spec.AddField(availability.FieldFriHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SatHours(); ok {
		_spec.SetField(availability.FieldSatHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSatHours(); ok {
		_spec.AddField(availability.FieldSatHours, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AvailabilityUpdateOne is the builder for updating a single Availability entity.
type AvailabilityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AvailabilityMutation
}

// SetSunHours sets the "sun_hours" field.
func (_u *AvailabilityUpdateOne) SetSunHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetSunHours()
	_u.mutation.SetSunHours(v)
	return _u
}

// SetNillableSunHours sets the "sun_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableSunHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetSunHours(*v)
	}
	return _u
}

// AddSunHours adds value to the "sun_hours" field.
func (_u *AvailabilityUpdateOne) AddSunHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddSunHours(v)
	return _u
}

// SetMonHours sets the "mon_hours" field.
func (_u *AvailabilityUpdateOne) SetMonHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetMonHours()
	_u.mutation.SetMonHours(v)
	return _u
}

// SetNillableMonHours sets the "mon_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableMonHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetMonHours(*v)
	}
	return _u
}

// AddMonHours adds value to the "mon_hours" field.
func (_u *AvailabilityUpdateOne) AddMonHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddMonHours(v)
	return _u
}

// SetTueHours sets the "tue_hours" field.
func (_u *AvailabilityUpdateOne) SetTueHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetTueHours()
	_u.mutation.SetTueHours(v)
	return _u
}

// SetNillableTueHours sets the "tue_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableTueHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetTueHours(*v)
	}
	return _u
}

// AddTueHours adds value to the "tue_hours" field.
func (_u *AvailabilityUpdateOne) AddTueHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddTueHours(v)
	return _u
}

// SetWedHours sets the "wed_hours" field.
func (_u *AvailabilityUpdateOne) SetWedHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetWedHours()
	_u.mutation.SetWedHours(v)
	return _u
}

// SetNillableWedHours sets the "wed_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableWedHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetWedHours(*v)
	}
	return _u
}

// AddWedHours adds value to the "wed_hours" field.
func (_u *AvailabilityUpdateOne) AddWedHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddWedHours(v)
	return _u
}

// SetThuHours sets the "thu_hours" field.
func (_u *AvailabilityUpdateOne) SetThuHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetThuHours()
	_u.mutation.SetThuHours(v)
	return _u
}

// SetNillableThuHours sets the "thu_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableThuHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetThuHours(*v)
	}
	return _u
}

// AddThuHours adds value to the "thu_hours" field.
func (_u *AvailabilityUpdateOne) AddThuHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddThuHours(v)
	return _u
}

// SetFriHours sets the "fri_hours" field.
func (_u *AvailabilityUpdateOne) SetFriHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetFriHours()
	_u.mutation.SetFriHours(v)
	return _u
}

// SetNillableFriHours sets the "fri_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableFriHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetFriHours(*v)
	}
	return _u
}

// AddFriHours adds value to the "fri_hours" field.
func (_u *AvailabilityUpdateOne) AddFriHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddFriHours(v)
	return _u
}

// SetSatHours sets the "sat_hours" field.
func (_u *AvailabilityUpdateOne) SetSatHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.ResetSatHours()
	_u.mutation.SetSatHours(v)
	return _u
}

// SetNillableSatHours sets the "sat_hours" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableSatHours(v *float64) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetSatHours(*v)
	}
	return _u
}

// AddSatHours adds value to the "sat_hours" field.
func (_u *AvailabilityUpdateOne) AddSatHours(v float64) *AvailabilityUpdateOne {
	_u.mutation.AddSatHours(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AvailabilityUpdateOne) SetUserID(id uuid.UUID) *AvailabilityUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AvailabilityUpdateOne) SetUser(v *User) *AvailabilityUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_u *AvailabilityUpdateOne) Mutation() *AvailabilityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AvailabilityUpdateOne) ClearUser() *AvailabilityUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AvailabilityUpdate builder.
func (_u *AvailabilityUpdateOne) Where(ps ...predicate.Availability) *AvailabilityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AvailabilityUpdateOne) Select(field string, fields ...string) *AvailabilityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Availability entity.
func (_u *AvailabilityUpdateOne) Save(ctx context.Context) (*Availability, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityUpdateOne) SaveX(ctx context.Context) *Availability {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AvailabilityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityUpdateOne) check() error {
	if v, ok := _u.mutation.SunHours(); ok {
		if err := availability.SunHoursValidator(v); err != nil {
			return &ValidationError{Name: "sun_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.sun_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MonHours(); ok {
		if err := availability.MonHoursValidator(v); err != nil {
			return &ValidationError{Name: "mon_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.mon_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TueHours(); ok {
		if err := availability.TueHoursValidator(v); err != nil {
			return &ValidationError{Name: "tue_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.tue_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WedHours(); ok {
		if err := availability.WedHoursValidator(v); err != nil {
			return &ValidationError{Name: "wed_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.wed_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThuHours(); ok {
		if err := availability.ThuHoursValidator(v); err != nil {
			return &ValidationError{Name: "thu_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.thu_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FriHours(); ok {
		if err := availability.FriHoursValidator(v); err != nil {
			return &ValidationError{Name: "fri_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.fri_hours": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SatHours(); ok {
		if err := availability.SatHoursValidator(v); err != nil {
			return &ValidationError{Name: "sat_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.sat_hours": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.user"`)
	}
	return nil
}

func (_u *AvailabilityUpdateOne) sqlSave(ctx context.Context) (_node *Availability, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availability.Table, availability.Columns, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Availability.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, availability.FieldID)
		for _, f := range fields {
			if !availability.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != availability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SunHours(); ok {
		_spec.SetField(availability.FieldSunHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSunHours(); ok {
		_spec.AddField(availability.FieldSunHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonHours(); ok {
		_spec.SetField(availability.FieldMonHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonHours(); ok {
		_spec.AddField(availability.FieldMonHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TueHours(); ok {
		_spec.SetField(availability.FieldTueHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTueHours(); ok {
		_spec.AddField(availability.FieldTueHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WedHours(); ok {
		_spec.SetField(availability.FieldWedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWedHours(); ok {
		_spec.AddField(availability.FieldWedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ThuHours(); ok {
		_spec.SetField(availability.FieldThuHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThuHours(); ok {
		_spec.AddField(availability.FieldThuHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FriHours(); ok {
		_spec.SetField(availability.FieldFriHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFriHours(); ok {
		_spec.AddField(availability.FieldFriHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SatHours(); ok {
		_spec.SetField(availability.FieldSatHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSatHours(); ok {
		_spec.AddField(availability.FieldSatHours, field.TypeFloat64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Availability{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
