// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/availability"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// AvailabilityCreate is the builder for creating a Availability entity.
type AvailabilityCreate struct {
	config
	mutation *AvailabilityMutation
	hooks    []Hook
}

// SetSunHours sets the "sun_hours" field.
func (_c *AvailabilityCreate) SetSunHours(v float64) *AvailabilityCreate {
	_c.mutation.SetSunHours(v)
	return _c
}

// SetNillableSunHours sets the "sun_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableSunHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetSunHours(*v)
	}
	return _c
}

// SetMonHours sets the "mon_hours" field.
func (_c *AvailabilityCreate) SetMonHours(v float64) *AvailabilityCreate {
	_c.mutation.SetMonHours(v)
	return _c
}

// SetNillableMonHours sets the "mon_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableMonHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetMonHours(*v)
	}
	return _c
}

// SetTueHours sets the "tue_hours" field.
func (_c *AvailabilityCreate) SetTueHours(v float64) *AvailabilityCreate {
	_c.mutation.SetTueHours(v)
	return _c
}

// SetNillableTueHours sets the "tue_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableTueHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetTueHours(*v)
	}
	return _c
}

// SetWedHours sets the "wed_hours" field.
func (_c *AvailabilityCreate) SetWedHours(v float64) *AvailabilityCreate {
	_c.mutation.SetWedHours(v)
	return _c
}

// SetNillableWedHours sets the "wed_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableWedHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetWedHours(*v)
	}
	return _c
}

// SetThuHours sets the "thu_hours" field.
func (_c *AvailabilityCreate) SetThuHours(v float64) *AvailabilityCreate {
	_c.mutation.SetThuHours(v)
	return _c
}

// SetNillableThuHours sets the "thu_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableThuHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetThuHours(*v)
	}
	return _c
}

// SetFriHours sets the "fri_hours" field.
func (_c *AvailabilityCreate) SetFriHours(v float64) *AvailabilityCreate {
	_c.mutation.SetFriHours(v)
	return _c
}

// SetNillableFriHours sets the "fri_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableFriHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetFriHours(*v)
	}
	return _c
}

// SetSatHours sets the "sat_hours" field.
func (_c *AvailabilityCreate) SetSatHours(v float64) *AvailabilityCreate {
	_c.mutation.SetSatHours(v)
	return _c
}

// SetNillableSatHours sets the "sat_hours" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableSatHours(v *float64) *AvailabilityCreate {
	if v != nil {
		_c.SetSatHours(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AvailabilityCreate) SetID(v uuid.UUID) *AvailabilityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AvailabilityCreate) SetNillableID(v *uuid.UUID) *AvailabilityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AvailabilityCreate) SetUserID(id uuid.UUID) *AvailabilityCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AvailabilityCreate) SetUser(v *User) *AvailabilityCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_c *AvailabilityCreate) Mutation() *AvailabilityMutation {
	return _c.mutation
}

// Save creates the Availability in the database.
func (_c *AvailabilityCreate) Save(ctx context.Context) (*Availability, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AvailabilityCreate) SaveX(ctx context.Context) *Availability {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AvailabilityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AvailabilityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AvailabilityCreate) defaults() {
	if _, ok := _c.mutation.SunHours(); !ok {
		v := availability.DefaultSunHours
		_c.mutation.SetSunHours(v)
	}
	if _, ok := _c.mutation.MonHours(); !ok {
		v := availability.DefaultMonHours
		_c.mutation.SetMonHours(v)
	}
	if _, ok := _c.mutation.TueHours(); !ok {
		v := availability.DefaultTueHours
		_c.mutation.SetTueHours(v)
	}
	if _, ok := _c.mutation.WedHours(); !ok {
		v := availability.DefaultWedHours
		_c.mutation.SetWedHours(v)
	}
	if _, ok := _c.mutation.ThuHours(); !ok {
		v := availability.DefaultThuHours
		_c.mutation.SetThuHours(v)
	}
	if _, ok := _c.mutation.FriHours(); !ok {
		v := availability.DefaultFriHours
		_c.mutation.SetFriHours(v)
	}
	if _, ok := _c.mutation.SatHours(); !ok {
		v := availability.DefaultSatHours
		_c.mutation.SetSatHours(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := availability.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AvailabilityCreate) check() error {
	if _, ok := _c.mutation.SunHours(); !ok {
		return &ValidationError{Name: "sun_hours", err: errors.New(`ent: missing required field "Availability.sun_hours"`)}
	}
	if v, ok := _c.mutation.SunHours(); ok {
		if err := availability.SunHoursValidator(v); err != nil {
			return &ValidationError{Name: "sun_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.sun_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MonHours(); !ok {
		return &ValidationError{Name: "mon_hours", err: errors.New(`ent: missing required field "Availability.mon_hours"`)}
	}
	if v, ok := _c.mutation.MonHours(); ok {
		if err := availability.MonHoursValidator(v); err != nil {
			return &ValidationError{Name: "mon_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.mon_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TueHours(); !ok {
		return &ValidationError{Name: "tue_hours", err: errors.New(`ent: missing required field "Availability.tue_hours"`)}
	}
	if v, ok := _c.mutation.TueHours(); ok {
		if err := availability.TueHoursValidator(v); err != nil {
			return &ValidationError{Name: "tue_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.tue_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WedHours(); !ok {
		return &ValidationError{Name: "wed_hours", err: errors.New(`ent: missing required field "Availability.wed_hours"`)}
	}
	if v, ok := _c.mutation.WedHours(); ok {
		if err := availability.WedHoursValidator(v); err != nil {
			return &ValidationError{Name: "wed_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.wed_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ThuHours(); !ok {
		return &ValidationError{Name: "thu_hours", err: errors.New(`ent: missing required field "Availability.thu_hours"`)}
	}
	if v, ok := _c.mutation.ThuHours(); ok {
		if err := availability.ThuHoursValidator(v); err != nil {
			return &ValidationError{Name: "thu_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.thu_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FriHours(); !ok {
		return &ValidationError{Name: "fri_hours", err: errors.New(`ent: missing required field "Availability.fri_hours"`)}
	}
	if v, ok := _c.mutation.FriHours(); ok {
		if err := availability.FriHoursValidator(v); err != nil {
			return &ValidationError{Name: "fri_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.fri_hours": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SatHours(); !ok {
		return &ValidationError{Name: "sat_hours", err: errors.New(`ent: missing required field "Availability.sat_hours"`)}
	}
	if v, ok := _c.mutation.SatHours(); ok {
		if err := availability.SatHoursValidator(v); err != nil {
			return &ValidationError{Name: "sat_hours", err: fmt.Errorf(`ent: validator failed for field "Availability.sat_hours": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Availability.user"`)}
	}
	return nil
}

func (_c *AvailabilityCreate) sqlSave(ctx context.Context) (*Availability, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AvailabilityCreate) createSpec() (*Availability, *sqlgraph.CreateSpec) {
	var (
		_node = &Availability{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(availability.Table, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SunHours(); ok {
		_spec.SetField(availability.FieldSunHours, field.TypeFloat64, value)
		_node.SunHours = value
	}
	if value, ok := _c.mutation.MonHours(); ok {
		_spec.SetField(availability.FieldMonHours, field.TypeFloat64, value)
		_node.MonHours = value
	}
	if value, ok := _c.mutation.TueHours(); ok {
		_spec.SetField(availability.FieldTueHours, field.TypeFloat64, value)
		_node.TueHours = value
	}
	if value, ok := _c.mutation.WedHours(); ok {
		_spec.SetField(availability.FieldWedHours, field.TypeFloat64, value)
		_node.WedHours = value
	}
	if value, ok := _c.mutation.ThuHours(); ok {
		_spec.SetField(availability.FieldThuHours, field.TypeFloat64, value)
		_node.ThuHours = value
	}
	if value, ok := _c.mutation.FriHours(); ok {
		_spec.SetField(availability.FieldFriHours, field.TypeFloat64, value)
		_node.FriHours = value
	}
	if value, ok := _c.mutation.SatHours(); ok {
		_spec.SetField(availability.FieldSatHours, field.TypeFloat64, value)
		_node.SatHours = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.UserTable,
			Columns: []string{availability.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_availabilities = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AvailabilityCreateBulk is the builder for creating many Availability entities in bulk.
type AvailabilityCreateBulk struct {
	config
	err      error
	builders []*AvailabilityCreate
}

// Save creates the Availability entities in the database.
func (_c *AvailabilityCreateBulk) Save(ctx context.Context) ([]*Availability, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Availability, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AvailabilityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AvailabilityCreateBulk) SaveX(ctx context.Context) []*Availability {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AvailabilityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AvailabilityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
