// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/dailytask"
	"github.com/hatamotoyuki/ninjo/backend/ent/plan"
)

// DailyTaskCreate is the builder for creating a DailyTask entity.
type DailyTaskCreate struct {
	config
	mutation *DailyTaskMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (_c *DailyTaskCreate) SetDate(v time.Time) *DailyTaskCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetStartPage sets the "start_page" field.
func (_c *DailyTaskCreate) SetStartPage(v int) *DailyTaskCreate {
	_c.mutation.SetStartPage(v)
	return _c
}

// SetEndPage sets the "end_page" field.
func (_c *DailyTaskCreate) SetEndPage(v int) *DailyTaskCreate {
	_c.mutation.SetEndPage(v)
	return _c
}

// SetActualEndPage sets the "actual_end_page" field.
func (_c *DailyTaskCreate) SetActualEndPage(v int) *DailyTaskCreate {
	_c.mutation.SetActualEndPage(v)
	return _c
}

// SetNillableActualEndPage sets the "actual_end_page" field if the given value is not nil.
func (_c *DailyTaskCreate) SetNillableActualEndPage(v *int) *DailyTaskCreate {
	if v != nil {
		_c.SetActualEndPage(*v)
	}
	return _c
}

// SetIsCompleted sets the "is_completed" field.
func (_c *DailyTaskCreate) SetIsCompleted(v bool) *DailyTaskCreate {
	_c.mutation.SetIsCompleted(v)
	return _c
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_c *DailyTaskCreate) SetNillableIsCompleted(v *bool) *DailyTaskCreate {
	if v != nil {
		_c.SetIsCompleted(*v)
	}
	return _c
}

// SetMemo sets the "memo" field.
func (_c *DailyTaskCreate) SetMemo(v string) *DailyTaskCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_c *DailyTaskCreate) SetNillableMemo(v *string) *DailyTaskCreate {
	if v != nil {
		_c.SetMemo(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DailyTaskCreate) SetCompletedAt(v time.Time) *DailyTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DailyTaskCreate) SetNillableCompletedAt(v *time.Time) *DailyTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DailyTaskCreate) SetCreatedAt(v time.Time) *DailyTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DailyTaskCreate) SetNillableCreatedAt(v *time.Time) *DailyTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DailyTaskCreate) SetID(v uuid.UUID) *DailyTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DailyTaskCreate) SetNillableID(v *uuid.UUID) *DailyTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_c *DailyTaskCreate) SetPlanID(id uuid.UUID) *DailyTaskCreate {
	_c.mutation.SetPlanID(id)
	return _c
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *DailyTaskCreate) SetPlan(v *Plan) *DailyTaskCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the DailyTaskMutation object of the builder.
func (_c *DailyTaskCreate) Mutation() *DailyTaskMutation {
	return _c.mutation
}

// Save creates the DailyTask in the database.
func (_c *DailyTaskCreate) Save(ctx context.Context) (*DailyTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyTaskCreate) SaveX(ctx context.Context) *DailyTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyTaskCreate) defaults() {
	if _, ok := _c.mutation.IsCompleted(); !ok {
		v := dailytask.DefaultIsCompleted
		_c.mutation.SetIsCompleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dailytask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dailytask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyTaskCreate) check() error {
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "DailyTask.date"`)}
	}
	if _, ok := _c.mutation.StartPage(); !ok {
		return &ValidationError{Name: "start_page", err: errors.New(`ent: missing required field "DailyTask.start_page"`)}
	}
	if v, ok := _c.mutation.StartPage(); ok {
		if err := dailytask.StartPageValidator(v); err != nil {
			return &ValidationError{Name: "start_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.start_page": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndPage(); !ok {
		return &ValidationError{Name: "end_page", err: errors.New(`ent: missing required field "DailyTask.end_page"`)}
	}
	if v, ok := _c.mutation.EndPage(); ok {
		if err := dailytask.EndPageValidator(v); err != nil {
			return &ValidationError{Name: "end_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.end_page": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ActualEndPage(); ok {
		if err := dailytask.ActualEndPageValidator(v); err != nil {
			return &ValidationError{Name: "actual_end_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.actual_end_page": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsCompleted(); !ok {
		return &ValidationError{Name: "is_completed", err: errors.New(`ent: missing required field "DailyTask.is_completed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DailyTask.created_at"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "DailyTask.plan"`)}
	}
	return nil
}

func (_c *DailyTaskCreate) sqlSave(ctx context.Context) (*DailyTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyTaskCreate) createSpec() (*DailyTask, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailytask.Table, sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(dailytask.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.StartPage(); ok {
		_spec.SetField(dailytask.FieldStartPage, field.TypeInt, value)
		_node.StartPage = value
	}
	if value, ok := _c.mutation.EndPage(); ok {
		_spec.SetField(dailytask.FieldEndPage, field.TypeInt, value)
		_node.EndPage = value
	}
	if value, ok := _c.mutation.ActualEndPage(); ok {
		_spec.SetField(dailytask.FieldActualEndPage, field.TypeInt, value)
		_node.ActualEndPage = &value
	}
	if value, ok := _c.mutation.IsCompleted(); ok {
		_spec.SetField(dailytask.FieldIsCompleted, field.TypeBool, value)
		_node.IsCompleted = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(dailytask.FieldMemo, field.TypeString, value)
		_node.Memo = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(dailytask.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dailytask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailytask.PlanTable,
			Columns: []string{dailytask.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.plan_daily_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DailyTaskCreateBulk is the builder for creating many DailyTask entities in bulk.
type DailyTaskCreateBulk struct {
	config
	err      error
	builders []*DailyTaskCreate
}

// Save creates the DailyTask entities in the database.
func (_c *DailyTaskCreateBulk) Save(ctx context.Context) ([]*DailyTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyTaskCreateBulk) SaveX(ctx context.Context) []*DailyTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
