// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/dailytask"
	"github.com/hatamotoyuki/ninjo/backend/ent/plan"
)

// DailyTask is the model entity for the DailyTask schema.
type DailyTask struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// StartPage holds the value of the "start_page" field.
	StartPage int `json:"start_page,omitempty"`
	// EndPage holds the value of the "end_page" field.
	EndPage int `json:"end_page,omitempty"`
	// ActualEndPage holds the value of the "actual_end_page" field.
	ActualEndPage *int `json:"actual_end_page,omitempty"`
	// IsCompleted holds the value of the "is_completed" field.
	IsCompleted bool `json:"is_completed,omitempty"`
	// Memo holds the value of the "memo" field.
	Memo *string `json:"memo,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DailyTaskQuery when eager-loading is set.
	Edges            DailyTaskEdges `json:"edges"`
	plan_daily_tasks *uuid.UUID
	selectValues     sql.SelectValues
}

// DailyTaskEdges holds the relations/edges for other nodes in the graph.
type DailyTaskEdges struct {
	// Plan holds the value of the plan edge.
	Plan *Plan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DailyTaskEdges) PlanOrErr() (*Plan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailytask.FieldIsCompleted:
			values[i] = new(sql.NullBool)
		case dailytask.FieldStartPage, dailytask.FieldEndPage, dailytask.FieldActualEndPage:
			values[i] = new(sql.NullInt64)
		case dailytask.FieldMemo:
			values[i] = new(sql.NullString)
		case dailytask.FieldDate, dailytask.FieldCompletedAt, dailytask.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case dailytask.FieldID:
			values[i] = new(uuid.UUID)
		case dailytask.ForeignKeys[0]: // plan_daily_tasks
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyTask fields.
func (_m *DailyTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailytask.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dailytask.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case dailytask.FieldStartPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_page", values[i])
			} else if value.Valid {
				_m.StartPage = int(value.Int64)
			}
		case dailytask.FieldEndPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_page", values[i])
			} else if value.Valid {
				_m.EndPage = int(value.Int64)
			}
		case dailytask.FieldActualEndPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_end_page", values[i])
			} else if value.Valid {
				_m.ActualEndPage = new(int)
				*_m.ActualEndPage = int(value.Int64)
			}
		case dailytask.FieldIsCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_completed", values[i])
			} else if value.Valid {
				_m.IsCompleted = value.Bool
			}
		case dailytask.FieldMemo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field memo", values[i])
			} else if value.Valid {
				_m.Memo = new(string)
				*_m.Memo = value.String
			}
		case dailytask.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case dailytask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dailytask.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field plan_daily_tasks", values[i])
			} else if value.Valid {
				_m.plan_daily_tasks = new(uuid.UUID)
				*_m.plan_daily_tasks = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyTask.
// This includes values selected through modifiers, order, etc.
func (_m *DailyTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the DailyTask entity.
func (_m *DailyTask) QueryPlan() *PlanQuery {
	return NewDailyTaskClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this DailyTask.
// Note that you need to call DailyTask.Unwrap() before calling this method if this DailyTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyTask) Update() *DailyTaskUpdateOne {
	return NewDailyTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyTask) Unwrap() *DailyTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyTask) String() string {
	var builder strings.Builder
	builder.WriteString("DailyTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("start_page=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartPage))
	builder.WriteString(", ")
	builder.WriteString("end_page=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndPage))
	builder.WriteString(", ")
	if v := _m.ActualEndPage; v != nil {
		builder.WriteString("actual_end_page=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCompleted))
	builder.WriteString(", ")
	if v := _m.Memo; v != nil {
		builder.WriteString("memo=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DailyTasks is a parsable slice of DailyTask.
type DailyTasks []*DailyTask
