// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hatamotoyuki/ninjo/backend/ent/dailytask"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
)

// DailyTaskDelete is the builder for deleting a DailyTask entity.
type DailyTaskDelete struct {
	config
	hooks    []Hook
	mutation *DailyTaskMutation
}

// Where appends a list predicates to the DailyTaskDelete builder.
func (_d *DailyTaskDelete) Where(ps ...predicate.DailyTask) *DailyTaskDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DailyTaskDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DailyTaskDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DailyTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dailytask.Table, sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DailyTaskDeleteOne is the builder for deleting a single DailyTask entity.
type DailyTaskDeleteOne struct {
	_d *DailyTaskDelete
}

// Where appends a list predicates to the DailyTaskDelete builder.
func (_d *DailyTaskDeleteOne) Where(ps ...predicate.DailyTask) *DailyTaskDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DailyTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dailytask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DailyTaskDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
