// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/dailytask"
	"github.com/hatamotoyuki/ninjo/backend/ent/plan"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
)

// DailyTaskUpdate is the builder for updating DailyTask entities.
type DailyTaskUpdate struct {
	config
	hooks    []Hook
	mutation *DailyTaskMutation
}

// Where appends a list predicates to the DailyTaskUpdate builder.
func (_u *DailyTaskUpdate) Where(ps ...predicate.DailyTask) *DailyTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDate sets the "date" field.
func (_u *DailyTaskUpdate) SetDate(v time.Time) *DailyTaskUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableDate(v *time.Time) *DailyTaskUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetStartPage sets the "start_page" field.
func (_u *DailyTaskUpdate) SetStartPage(v int) *DailyTaskUpdate {
	_u.mutation.ResetStartPage()
	_u.mutation.SetStartPage(v)
	return _u
}

// SetNillableStartPage sets the "start_page" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableStartPage(v *int) *DailyTaskUpdate {
	if v != nil {
		_u.SetStartPage(*v)
	}
	return _u
}

// AddStartPage adds value to the "start_page" field.
func (_u *DailyTaskUpdate) AddStartPage(v int) *DailyTaskUpdate {
	_u.mutation.AddStartPage(v)
	return _u
}

// SetEndPage sets the "end_page" field.
func (_u *DailyTaskUpdate) SetEndPage(v int) *DailyTaskUpdate {
	_u.mutation.ResetEndPage()
	_u.mutation.SetEndPage(v)
	return _u
}

// SetNillableEndPage sets the "end_page" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableEndPage(v *int) *DailyTaskUpdate {
	if v != nil {
		_u.SetEndPage(*v)
	}
	return _u
}

// AddEndPage adds value to the "end_page" field.
func (_u *DailyTaskUpdate) AddEndPage(v int) *DailyTaskUpdate {
	_u.mutation.AddEndPage(v)
	return _u
}

// SetActualEndPage sets the "actual_end_page" field.
func (_u *DailyTaskUpdate) SetActualEndPage(v int) *DailyTaskUpdate {
	_u.mutation.ResetActualEndPage()
	_u.mutation.SetActualEndPage(v)
	return _u
}

// SetNillableActualEndPage sets the "actual_end_page" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableActualEndPage(v *int) *DailyTaskUpdate {
	if v != nil {
		_u.SetActualEndPage(*v)
	}
	return _u
}

// AddActualEndPage adds value to the "actual_end_page" field.
func (_u *DailyTaskUpdate) AddActualEndPage(v int) *DailyTaskUpdate {
	_u.mutation.AddActualEndPage(v)
	return _u
}

// ClearActualEndPage clears the value of the "actual_end_page" field.
func (_u *DailyTaskUpdate) ClearActualEndPage() *DailyTaskUpdate {
	_u.mutation.ClearActualEndPage()
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *DailyTaskUpdate) SetIsCompleted(v bool) *DailyTaskUpdate {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableIsCompleted(v *bool) *DailyTaskUpdate {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *DailyTaskUpdate) SetMemo(v string) *DailyTaskUpdate {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableMemo(v *string) *DailyTaskUpdate {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *DailyTaskUpdate) ClearMemo() *DailyTaskUpdate {
	_u.mutation.ClearMemo()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DailyTaskUpdate) SetCompletedAt(v time.Time) *DailyTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DailyTaskUpdate) SetNillableCompletedAt(v *time.Time) *DailyTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DailyTaskUpdate) ClearCompletedAt() *DailyTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *DailyTaskUpdate) SetPlanID(id uuid.UUID) *DailyTaskUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *DailyTaskUpdate) SetPlan(v *Plan) *DailyTaskUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the DailyTaskMutation object of the builder.
func (_u *DailyTaskUpdate) Mutation() *DailyTaskMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *DailyTaskUpdate) ClearPlan() *DailyTaskUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyTaskUpdate) check() error {
	if v, ok := _u.mutation.StartPage(); ok {
		if err := dailytask.StartPageValidator(v); err != nil {
			return &ValidationError{Name: "start_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.start_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EndPage(); ok {
		if err := dailytask.EndPageValidator(v); err != nil {
			return &ValidationError{Name: "end_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.end_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualEndPage(); ok {
		if err := dailytask.ActualEndPageValidator(v); err != nil {
			return &ValidationError{Name: "actual_end_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.actual_end_page": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyTask.plan"`)
	}
	return nil
}

func (_u *DailyTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailytask.Table, dailytask.Columns, sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailytask.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartPage(); ok {
		_spec.SetField(dailytask.FieldStartPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartPage(); ok {
		_spec.AddField(dailytask.FieldStartPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndPage(); ok {
		_spec.SetField(dailytask.FieldEndPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndPage(); ok {
		_spec.AddField(dailytask.FieldEndPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActualEndPage(); ok {
		_spec.SetField(dailytask.FieldActualEndPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualEndPage(); ok {
		_spec.AddField(dailytask.FieldActualEndPage, field.TypeInt, value)
	}
	if _u.mutation.ActualEndPageCleared() {
		_spec.ClearField(dailytask.FieldActualEndPage, field.TypeInt)
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(dailytask.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(dailytask.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(dailytask.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(dailytask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(dailytask.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailytask.PlanTable,
			Columns: []string{dailytask.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailytask.PlanTable,
			Columns: []string{dailytask.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailytask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyTaskUpdateOne is the builder for updating a single DailyTask entity.
type DailyTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyTaskMutation
}

// SetDate sets the "date" field.
func (_u *DailyTaskUpdateOne) SetDate(v time.Time) *DailyTaskUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableDate(v *time.Time) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetStartPage sets the "start_page" field.
func (_u *DailyTaskUpdateOne) SetStartPage(v int) *DailyTaskUpdateOne {
	_u.mutation.ResetStartPage()
	_u.mutation.SetStartPage(v)
	return _u
}

// SetNillableStartPage sets the "start_page" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableStartPage(v *int) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetStartPage(*v)
	}
	return _u
}

// AddStartPage adds value to the "start_page" field.
func (_u *DailyTaskUpdateOne) AddStartPage(v int) *DailyTaskUpdateOne {
	_u.mutation.AddStartPage(v)
	return _u
}

// SetEndPage sets the "end_page" field.
func (_u *DailyTaskUpdateOne) SetEndPage(v int) *DailyTaskUpdateOne {
	_u.mutation.ResetEndPage()
	_u.mutation.SetEndPage(v)
	return _u
}

// SetNillableEndPage sets the "end_page" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableEndPage(v *int) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetEndPage(*v)
	}
	return _u
}

// AddEndPage adds value to the "end_page" field.
func (_u *DailyTaskUpdateOne) AddEndPage(v int) *DailyTaskUpdateOne {
	_u.mutation.AddEndPage(v)
	return _u
}

// SetActualEndPage sets the "actual_end_page" field.
func (_u *DailyTaskUpdateOne) SetActualEndPage(v int) *DailyTaskUpdateOne {
	_u.mutation.ResetActualEndPage()
	_u.mutation.SetActualEndPage(v)
	return _u
}

// SetNillableActualEndPage sets the "actual_end_page" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableActualEndPage(v *int) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetActualEndPage(*v)
	}
	return _u
}

// AddActualEndPage adds value to the "actual_end_page" field.
func (_u *DailyTaskUpdateOne) AddActualEndPage(v int) *DailyTaskUpdateOne {
	_u.mutation.AddActualEndPage(v)
	return _u
}

// ClearActualEndPage clears the value of the "actual_end_page" field.
func (_u *DailyTaskUpdateOne) ClearActualEndPage() *DailyTaskUpdateOne {
	_u.mutation.ClearActualEndPage()
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *DailyTaskUpdateOne) SetIsCompleted(v bool) *DailyTaskUpdateOne {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableIsCompleted(v *bool) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *DailyTaskUpdateOne) SetMemo(v string) *DailyTaskUpdateOne {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableMemo(v *string) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *DailyTaskUpdateOne) ClearMemo() *DailyTaskUpdateOne {
	_u.mutation.ClearMemo()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DailyTaskUpdateOne) SetCompletedAt(v time.Time) *DailyTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DailyTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *DailyTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DailyTaskUpdateOne) ClearCompletedAt() *DailyTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *DailyTaskUpdateOne) SetPlanID(id uuid.UUID) *DailyTaskUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *DailyTaskUpdateOne) SetPlan(v *Plan) *DailyTaskUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the DailyTaskMutation object of the builder.
func (_u *DailyTaskUpdateOne) Mutation() *DailyTaskMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *DailyTaskUpdateOne) ClearPlan() *DailyTaskUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the DailyTaskUpdate builder.
func (_u *DailyTaskUpdateOne) Where(ps ...predicate.DailyTask) *DailyTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyTaskUpdateOne) Select(field string, fields ...string) *DailyTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyTask entity.
func (_u *DailyTaskUpdateOne) Save(ctx context.Context) (*DailyTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyTaskUpdateOne) SaveX(ctx context.Context) *DailyTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyTaskUpdateOne) check() error {
	if v, ok := _u.mutation.StartPage(); ok {
		if err := dailytask.StartPageValidator(v); err != nil {
			return &ValidationError{Name: "start_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.start_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EndPage(); ok {
		if err := dailytask.EndPageValidator(v); err != nil {
			return &ValidationError{Name: "end_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.end_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualEndPage(); ok {
		if err := dailytask.ActualEndPageValidator(v); err != nil {
			return &ValidationError{Name: "actual_end_page", err: fmt.Errorf(`ent: validator failed for field "DailyTask.actual_end_page": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DailyTask.plan"`)
	}
	return nil
}

func (_u *DailyTaskUpdateOne) sqlSave(ctx context.Context) (_node *DailyTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailytask.Table, dailytask.Columns, sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailytask.FieldID)
		for _, f := range fields {
			if !dailytask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailytask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(dailytask.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartPage(); ok {
		_spec.SetField(dailytask.FieldStartPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartPage(); ok {
		_spec.AddField(dailytask.FieldStartPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndPage(); ok {
		_spec.SetField(dailytask.FieldEndPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndPage(); ok {
		_spec.AddField(dailytask.FieldEndPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActualEndPage(); ok {
		_spec.SetField(dailytask.FieldActualEndPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActualEndPage(); ok {
		_spec.AddField(dailytask.FieldActualEndPage, field.TypeInt, value)
	}
	if _u.mutation.ActualEndPageCleared() {
		_spec.ClearField(dailytask.FieldActualEndPage, field.TypeInt)
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(dailytask.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(dailytask.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(dailytask.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(dailytask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(dailytask.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailytask.PlanTable,
			Columns: []string{dailytask.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dailytask.PlanTable,
			Columns: []string{dailytask.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DailyTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailytask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
