// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/dailytask"
	"github.com/hatamotoyuki/ninjo/backend/ent/plan"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// PlanUpdate is the builder for updating Plan entities.
type PlanUpdate struct {
	config
	hooks    []Hook
	mutation *PlanMutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdate) Where(ps ...predicate.Plan) *PlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PlanUpdate) SetTitle(v string) *PlanUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableTitle(v *string) *PlanUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTotalPages sets the "total_pages" field.
func (_u *PlanUpdate) SetTotalPages(v int) *PlanUpdate {
	_u.mutation.ResetTotalPages()
	_u.mutation.SetTotalPages(v)
	return _u
}

// SetNillableTotalPages sets the "total_pages" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableTotalPages(v *int) *PlanUpdate {
	if v != nil {
		_u.SetTotalPages(*v)
	}
	return _u
}

// AddTotalPages adds value to the "total_pages" field.
func (_u *PlanUpdate) AddTotalPages(v int) *PlanUpdate {
	_u.mutation.AddTotalPages(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *PlanUpdate) SetStartDate(v time.Time) *PlanUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableStartDate(v *time.Time) *PlanUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *PlanUpdate) SetTargetDate(v time.Time) *PlanUpdate {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableTargetDate(v *time.Time) *PlanUpdate {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PlanUpdate) SetStatus(v plan.Status) *PlanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableStatus(v *plan.Status) *PlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAiReview sets the "ai_review" field.
func (_u *PlanUpdate) SetAiReview(v string) *PlanUpdate {
	_u.mutation.SetAiReview(v)
	return _u
}

// SetNillableAiReview sets the "ai_review" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableAiReview(v *string) *PlanUpdate {
	if v != nil {
		_u.SetAiReview(*v)
	}
	return _u
}

// ClearAiReview clears the value of the "ai_review" field.
func (_u *PlanUpdate) ClearAiReview() *PlanUpdate {
	_u.mutation.ClearAiReview()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanUpdate) SetUpdatedAt(v time.Time) *PlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PlanUpdate) SetUserID(id uuid.UUID) *PlanUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PlanUpdate) SetUser(v *User) *PlanUpdate {
	return _u.SetUserID(v.ID)
}

// AddDailyTaskIDs adds the "daily_tasks" edge to the DailyTask entity by IDs.
func (_u *PlanUpdate) AddDailyTaskIDs(ids ...uuid.UUID) *PlanUpdate {
	_u.mutation.AddDailyTaskIDs(ids...)
	return _u
}

// AddDailyTasks adds the "daily_tasks" edges to the DailyTask entity.
func (_u *PlanUpdate) AddDailyTasks(v ...*DailyTask) *PlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDailyTaskIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdate) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PlanUpdate) ClearUser() *PlanUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDailyTasks clears all "daily_tasks" edges to the DailyTask entity.
func (_u *PlanUpdate) ClearDailyTasks() *PlanUpdate {
	_u.mutation.ClearDailyTasks()
	return _u
}

// RemoveDailyTaskIDs removes the "daily_tasks" edge to DailyTask entities by IDs.
func (_u *PlanUpdate) RemoveDailyTaskIDs(ids ...uuid.UUID) *PlanUpdate {
	_u.mutation.RemoveDailyTaskIDs(ids...)
	return _u
}

// RemoveDailyTasks removes "daily_tasks" edges to DailyTask entities.
func (_u *PlanUpdate) RemoveDailyTasks(v ...*DailyTask) *PlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDailyTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := plan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Plan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalPages(); ok {
		if err := plan.TotalPagesValidator(v); err != nil {
			return &ValidationError{Name: "total_pages", err: fmt.Errorf(`ent: validator failed for field "Plan.total_pages": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := plan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plan.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Plan.user"`)
	}
	return nil
}

func (_u *PlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(plan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalPages(); ok {
		_spec.SetField(plan.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPages(); ok {
		_spec.AddField(plan.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(plan.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(plan.FieldTargetDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(plan.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AiReview(); ok {
		_spec.SetField(plan.FieldAiReview, field.TypeString, value)
	}
	if _u.mutation.AiReviewCleared() {
		_spec.ClearField(plan.FieldAiReview, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.UserTable,
			Columns: []string{plan.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.UserTable,
			Columns: []string{plan.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DailyTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.DailyTasksTable,
			Columns: []string{plan.DailyTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDailyTasksIDs(); len(nodes) > 0 && !_u.mutation.DailyTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.DailyTasksTable,
			Columns: []string{plan.DailyTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DailyTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.DailyTasksTable,
			Columns: []string{plan.DailyTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlanUpdateOne is the builder for updating a single Plan entity.
type PlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanMutation
}

// SetTitle sets the "title" field.
func (_u *PlanUpdateOne) SetTitle(v string) *PlanUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableTitle(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTotalPages sets the "total_pages" field.
func (_u *PlanUpdateOne) SetTotalPages(v int) *PlanUpdateOne {
	_u.mutation.ResetTotalPages()
	_u.mutation.SetTotalPages(v)
	return _u
}

// SetNillableTotalPages sets the "total_pages" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableTotalPages(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetTotalPages(*v)
	}
	return _u
}

// AddTotalPages adds value to the "total_pages" field.
func (_u *PlanUpdateOne) AddTotalPages(v int) *PlanUpdateOne {
	_u.mutation.AddTotalPages(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *PlanUpdateOne) SetStartDate(v time.Time) *PlanUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableStartDate(v *time.Time) *PlanUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetTargetDate sets the "target_date" field.
func (_u *PlanUpdateOne) SetTargetDate(v time.Time) *PlanUpdateOne {
	_u.mutation.SetTargetDate(v)
	return _u
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableTargetDate(v *time.Time) *PlanUpdateOne {
	if v != nil {
		_u.SetTargetDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PlanUpdateOne) SetStatus(v plan.Status) *PlanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableStatus(v *plan.Status) *PlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAiReview sets the "ai_review" field.
func (_u *PlanUpdateOne) SetAiReview(v string) *PlanUpdateOne {
	_u.mutation.SetAiReview(v)
	return _u
}

// SetNillableAiReview sets the "ai_review" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableAiReview(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetAiReview(*v)
	}
	return _u
}

// ClearAiReview clears the value of the "ai_review" field.
func (_u *PlanUpdateOne) ClearAiReview() *PlanUpdateOne {
	_u.mutation.ClearAiReview()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanUpdateOne) SetUpdatedAt(v time.Time) *PlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PlanUpdateOne) SetUserID(id uuid.UUID) *PlanUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PlanUpdateOne) SetUser(v *User) *PlanUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddDailyTaskIDs adds the "daily_tasks" edge to the DailyTask entity by IDs.
func (_u *PlanUpdateOne) AddDailyTaskIDs(ids ...uuid.UUID) *PlanUpdateOne {
	_u.mutation.AddDailyTaskIDs(ids...)
	return _u
}

// AddDailyTasks adds the "daily_tasks" edges to the DailyTask entity.
func (_u *PlanUpdateOne) AddDailyTasks(v ...*DailyTask) *PlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDailyTaskIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdateOne) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PlanUpdateOne) ClearUser() *PlanUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDailyTasks clears all "daily_tasks" edges to the DailyTask entity.
func (_u *PlanUpdateOne) ClearDailyTasks() *PlanUpdateOne {
	_u.mutation.ClearDailyTasks()
	return _u
}

// RemoveDailyTaskIDs removes the "daily_tasks" edge to DailyTask entities by IDs.
func (_u *PlanUpdateOne) RemoveDailyTaskIDs(ids ...uuid.UUID) *PlanUpdateOne {
	_u.mutation.RemoveDailyTaskIDs(ids...)
	return _u
}

// RemoveDailyTasks removes "daily_tasks" edges to DailyTask entities.
func (_u *PlanUpdateOne) RemoveDailyTasks(v ...*DailyTask) *PlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDailyTaskIDs(ids...)
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdateOne) Where(ps ...predicate.Plan) *PlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlanUpdateOne) Select(field string, fields ...string) *PlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plan entity.
func (_u *PlanUpdateOne) Save(ctx context.Context) (*Plan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdateOne) SaveX(ctx context.Context) *Plan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := plan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Plan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalPages(); ok {
		if err := plan.TotalPagesValidator(v); err != nil {
			return &ValidationError{Name: "total_pages", err: fmt.Errorf(`ent: validator failed for field "Plan.total_pages": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := plan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Plan.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Plan.user"`)
	}
	return nil
}

func (_u *PlanUpdateOne) sqlSave(ctx context.Context) (_node *Plan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for _, f := range fields {
			if !plan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(plan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalPages(); ok {
		_spec.SetField(plan.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPages(); ok {
		_spec.AddField(plan.FieldTotalPages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(plan.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TargetDate(); ok {
		_spec.SetField(plan.FieldTargetDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(plan.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AiReview(); ok {
		_spec.SetField(plan.FieldAiReview, field.TypeString, value)
	}
	if _u.mutation.AiReviewCleared() {
		_spec.ClearField(plan.FieldAiReview, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.UserTable,
			Columns: []string{plan.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plan.UserTable,
			Columns: []string{plan.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DailyTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.DailyTasksTable,
			Columns: []string{plan.DailyTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDailyTasksIDs(); len(nodes) > 0 && !_u.mutation.DailyTasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.DailyTasksTable,
			Columns: []string{plan.DailyTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DailyTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.DailyTasksTable,
			Columns: []string{plan.DailyTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dailytask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Plan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
