// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/plan"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// Plan is the model entity for the Plan schema.
type Plan struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// TotalPages holds the value of the "total_pages" field.
	TotalPages int `json:"total_pages,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// TargetDate holds the value of the "target_date" field.
	TargetDate time.Time `json:"target_date,omitempty"`
	// Status holds the value of the "status" field.
	Status plan.Status `json:"status,omitempty"`
	// AiReview holds the value of the "ai_review" field.
	AiReview *string `json:"ai_review,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlanQuery when eager-loading is set.
	Edges        PlanEdges `json:"edges"`
	user_plans   *uuid.UUID
	selectValues sql.SelectValues
}

// PlanEdges holds the relations/edges for other nodes in the graph.
type PlanEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// DailyTasks holds the value of the daily_tasks edge.
	DailyTasks []*DailyTask `json:"daily_tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlanEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DailyTasksOrErr returns the DailyTasks value or an error if the edge
// was not loaded in eager-loading.
func (e PlanEdges) DailyTasksOrErr() ([]*DailyTask, error) {
	if e.loadedTypes[1] {
		return e.DailyTasks, nil
	}
	return nil, &NotLoadedError{edge: "daily_tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plan.FieldTotalPages:
			values[i] = new(sql.NullInt64)
		case plan.FieldTitle, plan.FieldStatus, plan.FieldAiReview:
			values[i] = new(sql.NullString)
		case plan.FieldStartDate, plan.FieldTargetDate, plan.FieldCreatedAt, plan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case plan.FieldID:
			values[i] = new(uuid.UUID)
		case plan.ForeignKeys[0]: // user_plans
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plan fields.
func (_m *Plan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plan.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case plan.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case plan.FieldTotalPages:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_pages", values[i])
			} else if value.Valid {
				_m.TotalPages = int(value.Int64)
			}
		case plan.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case plan.FieldTargetDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field target_date", values[i])
			} else if value.Valid {
				_m.TargetDate = value.Time
			}
		case plan.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = plan.Status(value.String)
			}
		case plan.FieldAiReview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ai_review", values[i])
			} else if value.Valid {
				_m.AiReview = new(string)
				*_m.AiReview = value.String
			}
		case plan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case plan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case plan.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_plans", values[i])
			} else if value.Valid {
				_m.user_plans = new(uuid.UUID)
				*_m.user_plans = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Plan.
// This includes values selected through modifiers, order, etc.
func (_m *Plan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Plan entity.
func (_m *Plan) QueryUser() *UserQuery {
	return NewPlanClient(_m.config).QueryUser(_m)
}

// QueryDailyTasks queries the "daily_tasks" edge of the Plan entity.
func (_m *Plan) QueryDailyTasks() *DailyTaskQuery {
	return NewPlanClient(_m.config).QueryDailyTasks(_m)
}

// Update returns a builder for updating this Plan.
// Note that you need to call Plan.Unwrap() before calling this method if this Plan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Plan) Update() *PlanUpdateOne {
	return NewPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Plan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Plan) Unwrap() *Plan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Plan) String() string {
	var builder strings.Builder
	builder.WriteString("Plan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("total_pages=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPages))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("target_date=")
	builder.WriteString(_m.TargetDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.AiReview; v != nil {
		builder.WriteString("ai_review=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Plans is a parsable slice of Plan.
type Plans []*Plan
