// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/availability"
	"github.com/hatamotoyuki/ninjo/backend/ent/dailytask"
	"github.com/hatamotoyuki/ninjo/backend/ent/plan"
	"github.com/hatamotoyuki/ninjo/backend/ent/schema"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	availabilityFields := schema.Availability{}.Fields()
	_ = availabilityFields
	// availabilityDescDayOfWeek is the schema descriptor for day_of_week field.
	availabilityDescDayOfWeek := availabilityFields[1].Descriptor()
	// availability.DayOfWeekValidator is a validator for the "day_of_week" field. It is called by the builders before save.
	availability.DayOfWeekValidator = availabilityDescDayOfWeek.Validators[0].(func(int8) error)
	// availabilityDescHours is the schema descriptor for hours field.
	availabilityDescHours := availabilityFields[2].Descriptor()
	// availability.HoursValidator is a validator for the "hours" field. It is called by the builders before save.
	availability.HoursValidator = availabilityDescHours.Validators[0].(func(float64) error)
	// availabilityDescID is the schema descriptor for id field.
	availabilityDescID := availabilityFields[0].Descriptor()
	// availability.DefaultID holds the default value on creation for the id field.
	availability.DefaultID = availabilityDescID.Default.(func() uuid.UUID)
	dailytaskFields := schema.DailyTask{}.Fields()
	_ = dailytaskFields
	// dailytaskDescStartPage is the schema descriptor for start_page field.
	dailytaskDescStartPage := dailytaskFields[2].Descriptor()
	// dailytask.StartPageValidator is a validator for the "start_page" field. It is called by the builders before save.
	dailytask.StartPageValidator = dailytaskDescStartPage.Validators[0].(func(int) error)
	// dailytaskDescEndPage is the schema descriptor for end_page field.
	dailytaskDescEndPage := dailytaskFields[3].Descriptor()
	// dailytask.EndPageValidator is a validator for the "end_page" field. It is called by the builders before save.
	dailytask.EndPageValidator = dailytaskDescEndPage.Validators[0].(func(int) error)
	// dailytaskDescActualEndPage is the schema descriptor for actual_end_page field.
	dailytaskDescActualEndPage := dailytaskFields[4].Descriptor()
	// dailytask.ActualEndPageValidator is a validator for the "actual_end_page" field. It is called by the builders before save.
	dailytask.ActualEndPageValidator = dailytaskDescActualEndPage.Validators[0].(func(int) error)
	// dailytaskDescIsCompleted is the schema descriptor for is_completed field.
	dailytaskDescIsCompleted := dailytaskFields[5].Descriptor()
	// dailytask.DefaultIsCompleted holds the default value on creation for the is_completed field.
	dailytask.DefaultIsCompleted = dailytaskDescIsCompleted.Default.(bool)
	// dailytaskDescCreatedAt is the schema descriptor for created_at field.
	dailytaskDescCreatedAt := dailytaskFields[8].Descriptor()
	// dailytask.DefaultCreatedAt holds the default value on creation for the created_at field.
	dailytask.DefaultCreatedAt = dailytaskDescCreatedAt.Default.(func() time.Time)
	// dailytaskDescID is the schema descriptor for id field.
	dailytaskDescID := dailytaskFields[0].Descriptor()
	// dailytask.DefaultID holds the default value on creation for the id field.
	dailytask.DefaultID = dailytaskDescID.Default.(func() uuid.UUID)
	planFields := schema.Plan{}.Fields()
	_ = planFields
	// planDescTitle is the schema descriptor for title field.
	planDescTitle := planFields[1].Descriptor()
	// plan.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	plan.TitleValidator = func() func(string) error {
		validators := planDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// planDescTotalPages is the schema descriptor for total_pages field.
	planDescTotalPages := planFields[2].Descriptor()
	// plan.TotalPagesValidator is a validator for the "total_pages" field. It is called by the builders before save.
	plan.TotalPagesValidator = planDescTotalPages.Validators[0].(func(int) error)
	// planDescCreatedAt is the schema descriptor for created_at field.
	planDescCreatedAt := planFields[7].Descriptor()
	// plan.DefaultCreatedAt holds the default value on creation for the created_at field.
	plan.DefaultCreatedAt = planDescCreatedAt.Default.(func() time.Time)
	// planDescUpdatedAt is the schema descriptor for updated_at field.
	planDescUpdatedAt := planFields[8].Descriptor()
	// plan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plan.DefaultUpdatedAt = planDescUpdatedAt.Default.(func() time.Time)
	// plan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plan.UpdateDefaultUpdatedAt = planDescUpdatedAt.UpdateDefault.(func() time.Time)
	// planDescID is the schema descriptor for id field.
	planDescID := planFields[0].Descriptor()
	// plan.DefaultID holds the default value on creation for the id field.
	plan.DefaultID = planDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[3].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = func() func(string) error {
		validators := userDescDisplayName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(display_name string) error {
			for _, fn := range fns {
				if err := fn(display_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
