// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
	"github.com/hatamotoyuki/ninjo/backend/ent/skill"
	"github.com/hatamotoyuki/ninjo/backend/ent/user"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks    []Hook
	mutation *SkillMutation
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdate) SetName(v string) *SkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableName(v *string) *SkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SkillUpdate) SetCategory(v string) *SkillUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCategory(v *string) *SkillUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SkillUpdate) SetSource(v skill.Source) *SkillUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableSource(v *skill.Source) *SkillUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *SkillUpdate) SetTaskID(v uuid.UUID) *SkillUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableTaskID(v *uuid.UUID) *SkillUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *SkillUpdate) ClearTaskID() *SkillUpdate {
	_u.mutation.ClearTaskID()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SkillUpdate) SetUserID(id uuid.UUID) *SkillUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SkillUpdate) SetUser(v *User) *SkillUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdate) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SkillUpdate) ClearUser() *SkillUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := skill.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Skill.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := skill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Skill.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Skill.user"`)
	}
	return nil
}

func (_u *SkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(skill.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(skill.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(skill.FieldTaskID, field.TypeUUID, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(skill.FieldTaskID, field.TypeUUID)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkillMutation
}

// SetName sets the "name" field.
func (_u *SkillUpdateOne) SetName(v string) *SkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableName(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SkillUpdateOne) SetCategory(v string) *SkillUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCategory(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *SkillUpdateOne) SetSource(v skill.Source) *SkillUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableSource(v *skill.Source) *SkillUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *SkillUpdateOne) SetTaskID(v uuid.UUID) *SkillUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableTaskID(v *uuid.UUID) *SkillUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *SkillUpdateOne) ClearTaskID() *SkillUpdateOne {
	_u.mutation.ClearTaskID()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SkillUpdateOne) SetUserID(id uuid.UUID) *SkillUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SkillUpdateOne) SetUser(v *User) *SkillUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdateOne) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SkillUpdateOne) ClearUser() *SkillUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skill entity.
func (_u *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := skill.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Skill.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := skill.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Skill.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Skill.user"`)
	}
	return nil
}

func (_u *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(skill.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(skill.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(skill.FieldTaskID, field.TypeUUID, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(skill.FieldTaskID, field.TypeUUID)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Skill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
