// Code generated by ent, DO NOT EDIT.

package availability

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the availability type in the database.
	Label = "availability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDayOfWeek holds the string denoting the day_of_week field in the database.
	FieldDayOfWeek = "day_of_week"
	// FieldHours holds the string denoting the hours field in the database.
	FieldHours = "hours"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the availability in the database.
	Table = "availabilities"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "availabilities"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_availabilities"
)

// Columns holds all SQL columns for availability fields.
var Columns = []string{
	FieldID,
	FieldDayOfWeek,
	FieldHours,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "availabilities"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_availabilities",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DayOfWeekValidator is a validator for the "day_of_week" field. It is called by the builders before save.
	DayOfWeekValidator func(int8) error
	// HoursValidator is a validator for the "hours" field. It is called by the builders before save.
	HoursValidator func(float64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Availability queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDayOfWeek orders the results by the day_of_week field.
func ByDayOfWeek(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDayOfWeek, opts...).ToFunc()
}

// ByHours orders the results by the hours field.
func ByHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHours, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
