// Code generated by ent, DO NOT EDIT.

package availability

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the availability type in the database.
	Label = "availability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSunHours holds the string denoting the sun_hours field in the database.
	FieldSunHours = "sun_hours"
	// FieldMonHours holds the string denoting the mon_hours field in the database.
	FieldMonHours = "mon_hours"
	// FieldTueHours holds the string denoting the tue_hours field in the database.
	FieldTueHours = "tue_hours"
	// FieldWedHours holds the string denoting the wed_hours field in the database.
	FieldWedHours = "wed_hours"
	// FieldThuHours holds the string denoting the thu_hours field in the database.
	FieldThuHours = "thu_hours"
	// FieldFriHours holds the string denoting the fri_hours field in the database.
	FieldFriHours = "fri_hours"
	// FieldSatHours holds the string denoting the sat_hours field in the database.
	FieldSatHours = "sat_hours"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the availability in the database.
	Table = "availabilities"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "availabilities"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_availabilities"
)

// Columns holds all SQL columns for availability fields.
var Columns = []string{
	FieldID,
	FieldSunHours,
	FieldMonHours,
	FieldTueHours,
	FieldWedHours,
	FieldThuHours,
	FieldFriHours,
	FieldSatHours,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "availabilities"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_availabilities",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSunHours holds the default value on creation for the "sun_hours" field.
	DefaultSunHours float64
	// SunHoursValidator is a validator for the "sun_hours" field. It is called by the builders before save.
	SunHoursValidator func(float64) error
	// DefaultMonHours holds the default value on creation for the "mon_hours" field.
	DefaultMonHours float64
	// MonHoursValidator is a validator for the "mon_hours" field. It is called by the builders before save.
	MonHoursValidator func(float64) error
	// DefaultTueHours holds the default value on creation for the "tue_hours" field.
	DefaultTueHours float64
	// TueHoursValidator is a validator for the "tue_hours" field. It is called by the builders before save.
	TueHoursValidator func(float64) error
	// DefaultWedHours holds the default value on creation for the "wed_hours" field.
	DefaultWedHours float64
	// WedHoursValidator is a validator for the "wed_hours" field. It is called by the builders before save.
	WedHoursValidator func(float64) error
	// DefaultThuHours holds the default value on creation for the "thu_hours" field.
	DefaultThuHours float64
	// ThuHoursValidator is a validator for the "thu_hours" field. It is called by the builders before save.
	ThuHoursValidator func(float64) error
	// DefaultFriHours holds the default value on creation for the "fri_hours" field.
	DefaultFriHours float64
	// FriHoursValidator is a validator for the "fri_hours" field. It is called by the builders before save.
	FriHoursValidator func(float64) error
	// DefaultSatHours holds the default value on creation for the "sat_hours" field.
	DefaultSatHours float64
	// SatHoursValidator is a validator for the "sat_hours" field. It is called by the builders before save.
	SatHoursValidator func(float64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Availability queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySunHours orders the results by the sun_hours field.
func BySunHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSunHours, opts...).ToFunc()
}

// ByMonHours orders the results by the mon_hours field.
func ByMonHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonHours, opts...).ToFunc()
}

// ByTueHours orders the results by the tue_hours field.
func ByTueHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTueHours, opts...).ToFunc()
}

// ByWedHours orders the results by the wed_hours field.
func ByWedHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWedHours, opts...).ToFunc()
}

// ByThuHours orders the results by the thu_hours field.
func ByThuHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThuHours, opts...).ToFunc()
}

// ByFriHours orders the results by the fri_hours field.
func ByFriHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFriHours, opts...).ToFunc()
}

// BySatHours orders the results by the sat_hours field.
func BySatHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSatHours, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
