// Code generated by ent, DO NOT EDIT.

package availability

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldID, id))
}

// DayOfWeek applies equality check predicate on the "day_of_week" field. It's identical to DayOfWeekEQ.
func DayOfWeek(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldDayOfWeek, v))
}

// Hours applies equality check predicate on the "hours" field. It's identical to HoursEQ.
func Hours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldHours, v))
}

// DayOfWeekEQ applies the EQ predicate on the "day_of_week" field.
func DayOfWeekEQ(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldDayOfWeek, v))
}

// DayOfWeekNEQ applies the NEQ predicate on the "day_of_week" field.
func DayOfWeekNEQ(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldDayOfWeek, v))
}

// DayOfWeekIn applies the In predicate on the "day_of_week" field.
func DayOfWeekIn(vs ...int8) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldDayOfWeek, vs...))
}

// DayOfWeekNotIn applies the NotIn predicate on the "day_of_week" field.
func DayOfWeekNotIn(vs ...int8) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldDayOfWeek, vs...))
}

// DayOfWeekGT applies the GT predicate on the "day_of_week" field.
func DayOfWeekGT(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldDayOfWeek, v))
}

// DayOfWeekGTE applies the GTE predicate on the "day_of_week" field.
func DayOfWeekGTE(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldDayOfWeek, v))
}

// DayOfWeekLT applies the LT predicate on the "day_of_week" field.
func DayOfWeekLT(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldDayOfWeek, v))
}

// DayOfWeekLTE applies the LTE predicate on the "day_of_week" field.
func DayOfWeekLTE(v int8) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldDayOfWeek, v))
}

// HoursEQ applies the EQ predicate on the "hours" field.
func HoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldHours, v))
}

// HoursNEQ applies the NEQ predicate on the "hours" field.
func HoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldHours, v))
}

// HoursIn applies the In predicate on the "hours" field.
func HoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldHours, vs...))
}

// HoursNotIn applies the NotIn predicate on the "hours" field.
func HoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldHours, vs...))
}

// HoursGT applies the GT predicate on the "hours" field.
func HoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldHours, v))
}

// HoursGTE applies the GTE predicate on the "hours" field.
func HoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldHours, v))
}

// HoursLT applies the LT predicate on the "hours" field.
func HoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldHours, v))
}

// HoursLTE applies the LTE predicate on the "hours" field.
func HoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldHours, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.NotPredicates(p))
}
