// Code generated by ent, DO NOT EDIT.

package availability

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldID, id))
}

// SunHours applies equality check predicate on the "sun_hours" field. It's identical to SunHoursEQ.
func SunHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldSunHours, v))
}

// MonHours applies equality check predicate on the "mon_hours" field. It's identical to MonHoursEQ.
func MonHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldMonHours, v))
}

// TueHours applies equality check predicate on the "tue_hours" field. It's identical to TueHoursEQ.
func TueHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldTueHours, v))
}

// WedHours applies equality check predicate on the "wed_hours" field. It's identical to WedHoursEQ.
func WedHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldWedHours, v))
}

// ThuHours applies equality check predicate on the "thu_hours" field. It's identical to ThuHoursEQ.
func ThuHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldThuHours, v))
}

// FriHours applies equality check predicate on the "fri_hours" field. It's identical to FriHoursEQ.
func FriHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldFriHours, v))
}

// SatHours applies equality check predicate on the "sat_hours" field. It's identical to SatHoursEQ.
func SatHours(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldSatHours, v))
}

// SunHoursEQ applies the EQ predicate on the "sun_hours" field.
func SunHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldSunHours, v))
}

// SunHoursNEQ applies the NEQ predicate on the "sun_hours" field.
func SunHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldSunHours, v))
}

// SunHoursIn applies the In predicate on the "sun_hours" field.
func SunHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldSunHours, vs...))
}

// SunHoursNotIn applies the NotIn predicate on the "sun_hours" field.
func SunHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldSunHours, vs...))
}

// SunHoursGT applies the GT predicate on the "sun_hours" field.
func SunHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldSunHours, v))
}

// SunHoursGTE applies the GTE predicate on the "sun_hours" field.
func SunHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldSunHours, v))
}

// SunHoursLT applies the LT predicate on the "sun_hours" field.
func SunHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldSunHours, v))
}

// SunHoursLTE applies the LTE predicate on the "sun_hours" field.
func SunHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldSunHours, v))
}

// MonHoursEQ applies the EQ predicate on the "mon_hours" field.
func MonHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldMonHours, v))
}

// MonHoursNEQ applies the NEQ predicate on the "mon_hours" field.
func MonHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldMonHours, v))
}

// MonHoursIn applies the In predicate on the "mon_hours" field.
func MonHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldMonHours, vs...))
}

// MonHoursNotIn applies the NotIn predicate on the "mon_hours" field.
func MonHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldMonHours, vs...))
}

// MonHoursGT applies the GT predicate on the "mon_hours" field.
func MonHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldMonHours, v))
}

// MonHoursGTE applies the GTE predicate on the "mon_hours" field.
func MonHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldMonHours, v))
}

// MonHoursLT applies the LT predicate on the "mon_hours" field.
func MonHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldMonHours, v))
}

// MonHoursLTE applies the LTE predicate on the "mon_hours" field.
func MonHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldMonHours, v))
}

// TueHoursEQ applies the EQ predicate on the "tue_hours" field.
func TueHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldTueHours, v))
}

// TueHoursNEQ applies the NEQ predicate on the "tue_hours" field.
func TueHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldTueHours, v))
}

// TueHoursIn applies the In predicate on the "tue_hours" field.
func TueHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldTueHours, vs...))
}

// TueHoursNotIn applies the NotIn predicate on the "tue_hours" field.
func TueHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldTueHours, vs...))
}

// TueHoursGT applies the GT predicate on the "tue_hours" field.
func TueHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldTueHours, v))
}

// TueHoursGTE applies the GTE predicate on the "tue_hours" field.
func TueHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldTueHours, v))
}

// TueHoursLT applies the LT predicate on the "tue_hours" field.
func TueHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldTueHours, v))
}

// TueHoursLTE applies the LTE predicate on the "tue_hours" field.
func TueHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldTueHours, v))
}

// WedHoursEQ applies the EQ predicate on the "wed_hours" field.
func WedHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldWedHours, v))
}

// WedHoursNEQ applies the NEQ predicate on the "wed_hours" field.
func WedHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldWedHours, v))
}

// WedHoursIn applies the In predicate on the "wed_hours" field.
func WedHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldWedHours, vs...))
}

// WedHoursNotIn applies the NotIn predicate on the "wed_hours" field.
func WedHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldWedHours, vs...))
}

// WedHoursGT applies the GT predicate on the "wed_hours" field.
func WedHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldWedHours, v))
}

// WedHoursGTE applies the GTE predicate on the "wed_hours" field.
func WedHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldWedHours, v))
}

// WedHoursLT applies the LT predicate on the "wed_hours" field.
func WedHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldWedHours, v))
}

// WedHoursLTE applies the LTE predicate on the "wed_hours" field.
func WedHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldWedHours, v))
}

// ThuHoursEQ applies the EQ predicate on the "thu_hours" field.
func ThuHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldThuHours, v))
}

// ThuHoursNEQ applies the NEQ predicate on the "thu_hours" field.
func ThuHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldThuHours, v))
}

// ThuHoursIn applies the In predicate on the "thu_hours" field.
func ThuHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldThuHours, vs...))
}

// ThuHoursNotIn applies the NotIn predicate on the "thu_hours" field.
func ThuHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldThuHours, vs...))
}

// ThuHoursGT applies the GT predicate on the "thu_hours" field.
func ThuHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldThuHours, v))
}

// ThuHoursGTE applies the GTE predicate on the "thu_hours" field.
func ThuHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldThuHours, v))
}

// ThuHoursLT applies the LT predicate on the "thu_hours" field.
func ThuHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldThuHours, v))
}

// ThuHoursLTE applies the LTE predicate on the "thu_hours" field.
func ThuHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldThuHours, v))
}

// FriHoursEQ applies the EQ predicate on the "fri_hours" field.
func FriHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldFriHours, v))
}

// FriHoursNEQ applies the NEQ predicate on the "fri_hours" field.
func FriHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldFriHours, v))
}

// FriHoursIn applies the In predicate on the "fri_hours" field.
func FriHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldFriHours, vs...))
}

// FriHoursNotIn applies the NotIn predicate on the "fri_hours" field.
func FriHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldFriHours, vs...))
}

// FriHoursGT applies the GT predicate on the "fri_hours" field.
func FriHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldFriHours, v))
}

// FriHoursGTE applies the GTE predicate on the "fri_hours" field.
func FriHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldFriHours, v))
}

// FriHoursLT applies the LT predicate on the "fri_hours" field.
func FriHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldFriHours, v))
}

// FriHoursLTE applies the LTE predicate on the "fri_hours" field.
func FriHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldFriHours, v))
}

// SatHoursEQ applies the EQ predicate on the "sat_hours" field.
func SatHoursEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldSatHours, v))
}

// SatHoursNEQ applies the NEQ predicate on the "sat_hours" field.
func SatHoursNEQ(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldSatHours, v))
}

// SatHoursIn applies the In predicate on the "sat_hours" field.
func SatHoursIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldSatHours, vs...))
}

// SatHoursNotIn applies the NotIn predicate on the "sat_hours" field.
func SatHoursNotIn(vs ...float64) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldSatHours, vs...))
}

// SatHoursGT applies the GT predicate on the "sat_hours" field.
func SatHoursGT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldSatHours, v))
}

// SatHoursGTE applies the GTE predicate on the "sat_hours" field.
func SatHoursGTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldSatHours, v))
}

// SatHoursLT applies the LT predicate on the "sat_hours" field.
func SatHoursLT(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldSatHours, v))
}

// SatHoursLTE applies the LTE predicate on the "sat_hours" field.
func SatHoursLTE(v float64) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldSatHours, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.NotPredicates(p))
}
