// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AvailabilitiesColumns holds the columns for the "availabilities" table.
	AvailabilitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "sun_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "mon_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "tue_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "wed_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "thu_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "fri_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "sat_hours", Type: field.TypeFloat64, Default: 0},
		{Name: "user_availabilities", Type: field.TypeUUID},
	}
	// AvailabilitiesTable holds the schema information for the "availabilities" table.
	AvailabilitiesTable = &schema.Table{
		Name:       "availabilities",
		Columns:    AvailabilitiesColumns,
		PrimaryKey: []*schema.Column{AvailabilitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "availabilities_users_availabilities",
				Columns:    []*schema.Column{AvailabilitiesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DailyTasksColumns holds the columns for the "daily_tasks" table.
	DailyTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "date", Type: field.TypeTime},
		{Name: "start_page", Type: field.TypeInt},
		{Name: "end_page", Type: field.TypeInt},
		{Name: "actual_end_page", Type: field.TypeInt, Nullable: true},
		{Name: "is_completed", Type: field.TypeBool, Default: false},
		{Name: "memo", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "plan_daily_tasks", Type: field.TypeUUID},
	}
	// DailyTasksTable holds the schema information for the "daily_tasks" table.
	DailyTasksTable = &schema.Table{
		Name:       "daily_tasks",
		Columns:    DailyTasksColumns,
		PrimaryKey: []*schema.Column{DailyTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "daily_tasks_plans_daily_tasks",
				Columns:    []*schema.Column{DailyTasksColumns[9]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "dailytask_date_plan_daily_tasks",
				Unique:  false,
				Columns: []*schema.Column{DailyTasksColumns[1], DailyTasksColumns[9]},
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "total_pages", Type: field.TypeInt},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "target_date", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "completed", "paused"}, Default: "active"},
		{Name: "ai_review", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_plans", Type: field.TypeUUID},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plans_users_plans",
				Columns:    []*schema.Column{PlansColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "display_name", Type: field.TypeString, Size: 100},
		{Name: "avatar_preset_id", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AvailabilitiesTable,
		DailyTasksTable,
		PlansTable,
		UsersTable,
	}
)

func init() {
	AvailabilitiesTable.ForeignKeys[0].RefTable = UsersTable
	DailyTasksTable.ForeignKeys[0].RefTable = PlansTable
	PlansTable.ForeignKeys[0].RefTable = UsersTable
}
