// Code generated by ent, DO NOT EDIT.

package plan

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the plan type in the database.
	Label = "plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldTotalPages holds the string denoting the total_pages field in the database.
	FieldTotalPages = "total_pages"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldTargetDate holds the string denoting the target_date field in the database.
	FieldTargetDate = "target_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAiReview holds the string denoting the ai_review field in the database.
	FieldAiReview = "ai_review"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDailyTasks holds the string denoting the daily_tasks edge name in mutations.
	EdgeDailyTasks = "daily_tasks"
	// Table holds the table name of the plan in the database.
	Table = "plans"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "plans"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_plans"
	// DailyTasksTable is the table that holds the daily_tasks relation/edge.
	DailyTasksTable = "daily_tasks"
	// DailyTasksInverseTable is the table name for the DailyTask entity.
	// It exists in this package in order to avoid circular dependency with the "dailytask" package.
	DailyTasksInverseTable = "daily_tasks"
	// DailyTasksColumn is the table column denoting the daily_tasks relation/edge.
	DailyTasksColumn = "plan_daily_tasks"
)

// Columns holds all SQL columns for plan fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldTotalPages,
	FieldStartDate,
	FieldTargetDate,
	FieldStatus,
	FieldAiReview,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "plans"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_plans",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// TotalPagesValidator is a validator for the "total_pages" field. It is called by the builders before save.
	TotalPagesValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusCompleted Status = "completed"
	StatusPaused    Status = "paused"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusCompleted, StatusPaused:
		return nil
	default:
		return fmt.Errorf("plan: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Plan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByTotalPages orders the results by the total_pages field.
func ByTotalPages(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPages, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByTargetDate orders the results by the target_date field.
func ByTargetDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAiReview orders the results by the ai_review field.
func ByAiReview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAiReview, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDailyTasksCount orders the results by daily_tasks count.
func ByDailyTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDailyTasksStep(), opts...)
	}
}

// ByDailyTasks orders the results by daily_tasks terms.
func ByDailyTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDailyTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newDailyTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DailyTasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DailyTasksTable, DailyTasksColumn),
	)
}
