// Code generated by ent, DO NOT EDIT.

package plan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTitle, v))
}

// TotalPages applies equality check predicate on the "total_pages" field. It's identical to TotalPagesEQ.
func TotalPages(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTotalPages, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldStartDate, v))
}

// TargetDate applies equality check predicate on the "target_date" field. It's identical to TargetDateEQ.
func TargetDate(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTargetDate, v))
}

// AiReview applies equality check predicate on the "ai_review" field. It's identical to AiReviewEQ.
func AiReview(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldAiReview, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldTitle, v))
}

// TotalPagesEQ applies the EQ predicate on the "total_pages" field.
func TotalPagesEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTotalPages, v))
}

// TotalPagesNEQ applies the NEQ predicate on the "total_pages" field.
func TotalPagesNEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldTotalPages, v))
}

// TotalPagesIn applies the In predicate on the "total_pages" field.
func TotalPagesIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldTotalPages, vs...))
}

// TotalPagesNotIn applies the NotIn predicate on the "total_pages" field.
func TotalPagesNotIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldTotalPages, vs...))
}

// TotalPagesGT applies the GT predicate on the "total_pages" field.
func TotalPagesGT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldTotalPages, v))
}

// TotalPagesGTE applies the GTE predicate on the "total_pages" field.
func TotalPagesGTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldTotalPages, v))
}

// TotalPagesLT applies the LT predicate on the "total_pages" field.
func TotalPagesLT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldTotalPages, v))
}

// TotalPagesLTE applies the LTE predicate on the "total_pages" field.
func TotalPagesLTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldTotalPages, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldStartDate, v))
}

// TargetDateEQ applies the EQ predicate on the "target_date" field.
func TargetDateEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldTargetDate, v))
}

// TargetDateNEQ applies the NEQ predicate on the "target_date" field.
func TargetDateNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldTargetDate, v))
}

// TargetDateIn applies the In predicate on the "target_date" field.
func TargetDateIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldTargetDate, vs...))
}

// TargetDateNotIn applies the NotIn predicate on the "target_date" field.
func TargetDateNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldTargetDate, vs...))
}

// TargetDateGT applies the GT predicate on the "target_date" field.
func TargetDateGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldTargetDate, v))
}

// TargetDateGTE applies the GTE predicate on the "target_date" field.
func TargetDateGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldTargetDate, v))
}

// TargetDateLT applies the LT predicate on the "target_date" field.
func TargetDateLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldTargetDate, v))
}

// TargetDateLTE applies the LTE predicate on the "target_date" field.
func TargetDateLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldTargetDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldStatus, vs...))
}

// AiReviewEQ applies the EQ predicate on the "ai_review" field.
func AiReviewEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldAiReview, v))
}

// AiReviewNEQ applies the NEQ predicate on the "ai_review" field.
func AiReviewNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldAiReview, v))
}

// AiReviewIn applies the In predicate on the "ai_review" field.
func AiReviewIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldAiReview, vs...))
}

// AiReviewNotIn applies the NotIn predicate on the "ai_review" field.
func AiReviewNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldAiReview, vs...))
}

// AiReviewGT applies the GT predicate on the "ai_review" field.
func AiReviewGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldAiReview, v))
}

// AiReviewGTE applies the GTE predicate on the "ai_review" field.
func AiReviewGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldAiReview, v))
}

// AiReviewLT applies the LT predicate on the "ai_review" field.
func AiReviewLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldAiReview, v))
}

// AiReviewLTE applies the LTE predicate on the "ai_review" field.
func AiReviewLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldAiReview, v))
}

// AiReviewContains applies the Contains predicate on the "ai_review" field.
func AiReviewContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldAiReview, v))
}

// AiReviewHasPrefix applies the HasPrefix predicate on the "ai_review" field.
func AiReviewHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldAiReview, v))
}

// AiReviewHasSuffix applies the HasSuffix predicate on the "ai_review" field.
func AiReviewHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldAiReview, v))
}

// AiReviewIsNil applies the IsNil predicate on the "ai_review" field.
func AiReviewIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldAiReview))
}

// AiReviewNotNil applies the NotNil predicate on the "ai_review" field.
func AiReviewNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldAiReview))
}

// AiReviewEqualFold applies the EqualFold predicate on the "ai_review" field.
func AiReviewEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldAiReview, v))
}

// AiReviewContainsFold applies the ContainsFold predicate on the "ai_review" field.
func AiReviewContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldAiReview, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDailyTasks applies the HasEdge predicate on the "daily_tasks" edge.
func HasDailyTasks() predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DailyTasksTable, DailyTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDailyTasksWith applies the HasEdge predicate on the "daily_tasks" edge with a given conditions (other predicates).
func HasDailyTasksWith(preds ...predicate.DailyTask) predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := newDailyTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.NotPredicates(p))
}
