// Code generated by ent, DO NOT EDIT.

package dailytask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the dailytask type in the database.
	Label = "daily_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldStartPage holds the string denoting the start_page field in the database.
	FieldStartPage = "start_page"
	// FieldEndPage holds the string denoting the end_page field in the database.
	FieldEndPage = "end_page"
	// FieldActualEndPage holds the string denoting the actual_end_page field in the database.
	FieldActualEndPage = "actual_end_page"
	// FieldIsCompleted holds the string denoting the is_completed field in the database.
	FieldIsCompleted = "is_completed"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// Table holds the table name of the dailytask in the database.
	Table = "daily_tasks"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "daily_tasks"
	// PlanInverseTable is the table name for the Plan entity.
	// It exists in this package in order to avoid circular dependency with the "plan" package.
	PlanInverseTable = "plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_daily_tasks"
)

// Columns holds all SQL columns for dailytask fields.
var Columns = []string{
	FieldID,
	FieldDate,
	FieldStartPage,
	FieldEndPage,
	FieldActualEndPage,
	FieldIsCompleted,
	FieldMemo,
	FieldCompletedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "daily_tasks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"plan_daily_tasks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// StartPageValidator is a validator for the "start_page" field. It is called by the builders before save.
	StartPageValidator func(int) error
	// EndPageValidator is a validator for the "end_page" field. It is called by the builders before save.
	EndPageValidator func(int) error
	// ActualEndPageValidator is a validator for the "actual_end_page" field. It is called by the builders before save.
	ActualEndPageValidator func(int) error
	// DefaultIsCompleted holds the default value on creation for the "is_completed" field.
	DefaultIsCompleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DailyTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByStartPage orders the results by the start_page field.
func ByStartPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartPage, opts...).ToFunc()
}

// ByEndPage orders the results by the end_page field.
func ByEndPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndPage, opts...).ToFunc()
}

// ByActualEndPage orders the results by the actual_end_page field.
func ByActualEndPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualEndPage, opts...).ToFunc()
}

// ByIsCompleted orders the results by the is_completed field.
func ByIsCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCompleted, opts...).ToFunc()
}

// ByMemo orders the results by the memo field.
func ByMemo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemo, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
	)
}
