// Code generated by ent, DO NOT EDIT.

package dailytask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/hatamotoyuki/ninjo/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldID, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldDate, v))
}

// StartPage applies equality check predicate on the "start_page" field. It's identical to StartPageEQ.
func StartPage(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldStartPage, v))
}

// EndPage applies equality check predicate on the "end_page" field. It's identical to EndPageEQ.
func EndPage(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldEndPage, v))
}

// ActualEndPage applies equality check predicate on the "actual_end_page" field. It's identical to ActualEndPageEQ.
func ActualEndPage(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldActualEndPage, v))
}

// IsCompleted applies equality check predicate on the "is_completed" field. It's identical to IsCompletedEQ.
func IsCompleted(v bool) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldIsCompleted, v))
}

// Memo applies equality check predicate on the "memo" field. It's identical to MemoEQ.
func Memo(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldMemo, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldCreatedAt, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldDate, v))
}

// StartPageEQ applies the EQ predicate on the "start_page" field.
func StartPageEQ(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldStartPage, v))
}

// StartPageNEQ applies the NEQ predicate on the "start_page" field.
func StartPageNEQ(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldStartPage, v))
}

// StartPageIn applies the In predicate on the "start_page" field.
func StartPageIn(vs ...int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldStartPage, vs...))
}

// StartPageNotIn applies the NotIn predicate on the "start_page" field.
func StartPageNotIn(vs ...int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldStartPage, vs...))
}

// StartPageGT applies the GT predicate on the "start_page" field.
func StartPageGT(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldStartPage, v))
}

// StartPageGTE applies the GTE predicate on the "start_page" field.
func StartPageGTE(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldStartPage, v))
}

// StartPageLT applies the LT predicate on the "start_page" field.
func StartPageLT(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldStartPage, v))
}

// StartPageLTE applies the LTE predicate on the "start_page" field.
func StartPageLTE(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldStartPage, v))
}

// EndPageEQ applies the EQ predicate on the "end_page" field.
func EndPageEQ(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldEndPage, v))
}

// EndPageNEQ applies the NEQ predicate on the "end_page" field.
func EndPageNEQ(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldEndPage, v))
}

// EndPageIn applies the In predicate on the "end_page" field.
func EndPageIn(vs ...int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldEndPage, vs...))
}

// EndPageNotIn applies the NotIn predicate on the "end_page" field.
func EndPageNotIn(vs ...int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldEndPage, vs...))
}

// EndPageGT applies the GT predicate on the "end_page" field.
func EndPageGT(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldEndPage, v))
}

// EndPageGTE applies the GTE predicate on the "end_page" field.
func EndPageGTE(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldEndPage, v))
}

// EndPageLT applies the LT predicate on the "end_page" field.
func EndPageLT(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldEndPage, v))
}

// EndPageLTE applies the LTE predicate on the "end_page" field.
func EndPageLTE(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldEndPage, v))
}

// ActualEndPageEQ applies the EQ predicate on the "actual_end_page" field.
func ActualEndPageEQ(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldActualEndPage, v))
}

// ActualEndPageNEQ applies the NEQ predicate on the "actual_end_page" field.
func ActualEndPageNEQ(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldActualEndPage, v))
}

// ActualEndPageIn applies the In predicate on the "actual_end_page" field.
func ActualEndPageIn(vs ...int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldActualEndPage, vs...))
}

// ActualEndPageNotIn applies the NotIn predicate on the "actual_end_page" field.
func ActualEndPageNotIn(vs ...int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldActualEndPage, vs...))
}

// ActualEndPageGT applies the GT predicate on the "actual_end_page" field.
func ActualEndPageGT(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldActualEndPage, v))
}

// ActualEndPageGTE applies the GTE predicate on the "actual_end_page" field.
func ActualEndPageGTE(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldActualEndPage, v))
}

// ActualEndPageLT applies the LT predicate on the "actual_end_page" field.
func ActualEndPageLT(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldActualEndPage, v))
}

// ActualEndPageLTE applies the LTE predicate on the "actual_end_page" field.
func ActualEndPageLTE(v int) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldActualEndPage, v))
}

// ActualEndPageIsNil applies the IsNil predicate on the "actual_end_page" field.
func ActualEndPageIsNil() predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIsNull(FieldActualEndPage))
}

// ActualEndPageNotNil applies the NotNil predicate on the "actual_end_page" field.
func ActualEndPageNotNil() predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotNull(FieldActualEndPage))
}

// IsCompletedEQ applies the EQ predicate on the "is_completed" field.
func IsCompletedEQ(v bool) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldIsCompleted, v))
}

// IsCompletedNEQ applies the NEQ predicate on the "is_completed" field.
func IsCompletedNEQ(v bool) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldIsCompleted, v))
}

// MemoEQ applies the EQ predicate on the "memo" field.
func MemoEQ(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldMemo, v))
}

// MemoNEQ applies the NEQ predicate on the "memo" field.
func MemoNEQ(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldMemo, v))
}

// MemoIn applies the In predicate on the "memo" field.
func MemoIn(vs ...string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldMemo, vs...))
}

// MemoNotIn applies the NotIn predicate on the "memo" field.
func MemoNotIn(vs ...string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldMemo, vs...))
}

// MemoGT applies the GT predicate on the "memo" field.
func MemoGT(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldMemo, v))
}

// MemoGTE applies the GTE predicate on the "memo" field.
func MemoGTE(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldMemo, v))
}

// MemoLT applies the LT predicate on the "memo" field.
func MemoLT(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldMemo, v))
}

// MemoLTE applies the LTE predicate on the "memo" field.
func MemoLTE(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldMemo, v))
}

// MemoContains applies the Contains predicate on the "memo" field.
func MemoContains(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldContains(FieldMemo, v))
}

// MemoHasPrefix applies the HasPrefix predicate on the "memo" field.
func MemoHasPrefix(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldHasPrefix(FieldMemo, v))
}

// MemoHasSuffix applies the HasSuffix predicate on the "memo" field.
func MemoHasSuffix(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldHasSuffix(FieldMemo, v))
}

// MemoIsNil applies the IsNil predicate on the "memo" field.
func MemoIsNil() predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIsNull(FieldMemo))
}

// MemoNotNil applies the NotNil predicate on the "memo" field.
func MemoNotNil() predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotNull(FieldMemo))
}

// MemoEqualFold applies the EqualFold predicate on the "memo" field.
func MemoEqualFold(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEqualFold(FieldMemo, v))
}

// MemoContainsFold applies the ContainsFold predicate on the "memo" field.
func MemoContainsFold(v string) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldContainsFold(FieldMemo, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DailyTask {
	return predicate.DailyTask(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.DailyTask {
	return predicate.DailyTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.Plan) predicate.DailyTask {
	return predicate.DailyTask(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyTask) predicate.DailyTask {
	return predicate.DailyTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyTask) predicate.DailyTask {
	return predicate.DailyTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyTask) predicate.DailyTask {
	return predicate.DailyTask(sql.NotPredicates(p))
}
